### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by misaka00251** [dataabc/weiboSpider#17]
```
用户名: 新浪
Error:  list index out of range
Traceback (most recent call last):
  File "weiboSpider.py", line 56, in get_user_info
    "//div[@class='tip2']/span[@class='tc']/text()")[0]
IndexError: list index out of range
Error:  list index out of range
Traceback (most recent call last):
  File "weiboSpider.py", line 113, in get_weibo_info
    is_empty = info[0].xpath("div/span[@class='ctt']")
IndexError: list index out of range
```

**Comment by dataabc** [comment]
如果没想错，你的cookie没有写对。按照README获取cookie,把your cookie 替换成你获取的cookie就可以正确运行

**Comment by misaka00251** [comment]
```
SUB=xxx; SCF=xxx; SSOLoginState=xxx; _T_WM=xxx; WEIBOCN_FROM=xxx; M_WEIBOCN_PARAMS=xxx"
```
Cookie 里有这些内容，直接复制粘贴的...

**Comment by dataabc** [comment]
刚才试了一遍，可以正确运行。我认为可能是cookie没有正确获取或者过期了，你可以退出登录，按readme重新获取。因为这个错误很可能是cookie，我以前见过类似的错误，修改cookie就可以了。如果还出错，可以告诉我被爬微博的id(如果方便的话)，我测试下

**Comment by misaka00251** [comment]
果然是 Cookie 的错误 ...

**Comment by zhouenbo** [comment]
请问这个问题后来是怎么解决的，我确实按照readme获取的cookie，但是出现了和楼主一样的问题
