### ISSUE TITLE
刚刚重新下载最新，不能正常运行

### ISSUE THREAD

**Issue by gudaost** [dataabc/weiboSpider#182]
为了更好的解决问题，请认真回答下面的问题。等到问题解决，请及时关闭本issue。<br>

- 问：请您指明哪个版本运行出错（github版/PyPi版/全部）？<br>
答：py 3.8.3

- 问：您使用的是否是最新的程序（是/否）？<br>
答：是

- 问：爬取任意用户都会运行出错吗（是/否）？<br>
答：是

- 问：若只有爬特定微博时才出错，能否提供出错微博的weibo_id或url（非必填）？<br>
答：

- 问：若您已提供出错微博的weibo_id或url，可忽略此内容，否则能否提供出错账号的**user_id**及您配置的**since_date**，方便我们定位出错微博（非必填）？<br>
答：

- 问：如果方便，请您描述出错详情，最好附上错误提示。<br>
答：“user_id_list.txt”使用的是weibo_spider文件夹中提供的那个（内容只保留了7053204102）

Error:  list index out of range
Traceback (most recent call last):
  File "X:\Program Files\Pic_Follow_WeiBo\Cookie版\weibo_spider\parser\info_parser.py", line 37, in extract_user_info
    if self.selector.xpath(
IndexError: list index out of range
Error:  'NoneType' object has no attribute 'id'
Traceback (most recent call last):
  File "X:\Program Files\Pic_Follow_WeiBo\Cookie版\weibo_spider\parser\index_parser.py", line 34, in get_user
    self.user.id = user_id
AttributeError: 'NoneType' object has no attribute 'id'
None
****************************************************************************************************
Error:  'NoneType' object has no attribute 'nickname'
Traceback (most recent call last):
  File "X:\Program Files\Pic_Follow_WeiBo\Cookie版\weibo_spider\spider.py", line 137, in _get_filepath
    self.user.nickname)
AttributeError: 'NoneType' object has no attribute 'nickname'
Error:  expected str, bytes or os.PathLike object, not NoneType
Traceback (most recent call last):
  File "X:\Program Files\Pic_Follow_WeiBo\Cookie版\weibo_spider\writer\csv_writer.py", line 23, in __init__
    with open(self.file_path, "a", encoding="utf-8-sig",
TypeError: expected str, bytes or os.PathLike object, not NoneType
Error:  'NoneType' object has no attribute 'nickname'
Traceback (most recent call last):
  File "X:\Program Files\Pic_Follow_WeiBo\Cookie版\weibo_spider\spider.py", line 137, in _get_filepath
    self.user.nickname)
AttributeError: 'NoneType' object has no attribute 'nickname'
****************************************************************************************************
Progress:   0%|                                                                                 | 0/50 [00:00<?, ?it/s]
Error:  'NoneType' object has no attribute 'nickname'
Traceback (most recent call last):
  File "X:\Program Files\Pic_Follow_WeiBo\Cookie版\weibo_spider\spider.py", line 109, in get_weibo_info
    self.user.nickname,
AttributeError: 'NoneType' object has no attribute 'nickname'
共爬取0条微博
信息抓取完毕

**Comment by dataabc** [comment]
感谢反馈。

可能原因有两个：

1.config.json中的user_id_list不正确，如果想填写文件路径，应该是字符串，如果想填user_id，应该是列表；
2.速度太快，降低速度就可以，参考[常见问题](https://github.com/dataabc/weiboSpider/blob/master/docs/FAQ.md)的第二个问题。

如果还有问题或建议，欢迎继续讨论

**Comment by gudaost** [comment]
多谢！是json文件里面配置错了，使用的"user_id_list.txt"结果忘记去掉[]了，不好意思
