### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by peijunlin2008** [dataabc/weiboSpider#199]
Traceback (most recent call last):
  File "D:\Git_Source\python_learning\weiboSpider\weibo_spider\parser\info_parser.py", line 39, in extract_user_info
    if self.selector.xpath(
IndexError: list index out of range
2020-07-31 19:18:50,060 - ERROR - index_parser.py[:44] - 'NoneType' object has no attribute 'id'
Traceback (most recent call last):
  File "D:\Git_Source\python_learning\weiboSpider\weibo_spider\parser\index_parser.py", line 36, in get_user
    self.user.id = user_id
AttributeError: 'NoneType' object has no attribute 'id'
2020-07-31 19:18:50,173 - ERROR - spider.py[:195] - 'NoneType' object has no attribute 'nickname'
Traceback (most recent call last):
  File "D:\Git_Source\python_learning\weiboSpider\weibo_spider\spider.py", line 185, in _get_filepath
    self.user.nickname)
AttributeError: 'NoneType' object has no attribute 'nickname'
2020-07-31 19:18:50,175 - ERROR - csv_writer.py[:30] - expected str, bytes or os.PathLike object, not NoneType
Traceback (most recent call last):
  File "D:\Git_Source\python_learning\weiboSpider\weibo_spider\writer\csv_writer.py", line 25, in __init__
    with open(self.file_path, 'a', encoding='utf-8-sig',
TypeError: expected str, bytes or os.PathLike object, not NoneType
2020-07-31 19:18:50,178 - ERROR - spider.py[:195] - 'NoneType' object has no attribute 'nickname'
Traceback (most recent call last):
  File "D:\Git_Source\python_learning\weiboSpider\weibo_spider\spider.py", line 185, in _get_filepath
    self.user.nickname)
AttributeError: 'NoneType' object has no attribute 'nickname'
2020-07-31 19:18:50,189 - ERROR - spider.py[:195] - 'NoneType' object has no attribute 'nickname'
Traceback (most recent call last):
  File "D:\Git_Source\python_learning\weiboSpider\weibo_spider\spider.py", line 185, in _get_filepath
    self.user.nickname)
AttributeError: 'NoneType' object has no attribute 'nickname'
2020-07-31 19:18:50,190 - ERROR - spider.py[:195] - 'NoneType' object has no attribute 'nickname'
Traceback (most recent call last):
  File "D:\Git_Source\python_learning\weiboSpider\weibo_spider\spider.py", line 185, in _get_filepath
    self.user.nickname)
AttributeError: 'NoneType' object has no attribute 'nickname'
2020-07-31 19:18:50,191 - ERROR - spider.py[:283] - 'NoneType' object has no attribute '__dict__'
Traceback (most recent call last):
  File "D:\Git_Source\python_learning\weiboSpider\weibo_spider\spider.py", line 262, in start
    self.write_user(self.user)
  File "D:\Git_Source\python_learning\weiboSpider\weibo_spider\spider.py", line 110, in write_user
    writer.write_user(user)
  File "D:\Git_Source\python_learning\weiboSpider\weibo_spider\writer\txt_writer.py", line 29, in write_user
    [v + '：' + str(self.user.__dict__[k]) for k, v in self.user_desc])
  File "D:\Git_Source\python_learning\weiboSpider\weibo_spider\writer\txt_writer.py", line 29, in <listcomp>
    [v + '：' + str(self.user.__dict__[k]) for k, v in self.user_desc])
AttributeError: 'NoneType' object has no attribute '__dict__'

**Comment by dataabc** [comment]
感谢反馈。

这是速度太快被限制了，限制一段时间会自动解除。可以通过配置config,json减速：
```
    "random_wait_pages": [1, 5],
    "random_wait_seconds": [6, 10],
    "global_wait": [[1000, 3600], [500, 2000]],    
```
前两行的意思是每爬取1到5页，随机等待6到10秒。可以通过加快暂停频率（减小random_wait_pages内的值）或增加等待时间（加大random_wait_seconds内的值）避免被限制。最后一行的意思是获取1000页微博，一次性等待3600秒；之后获取500页微博一次性等待2000秒。默认只有两个global_wait配置（[1000, 3600]和[500, 2000]），可以添加更多个，也可以自定义。当配置使用完，如默认配置在获取1500（1000+500）页微博后就用完了，之后程序会从第一个配置开始循环使用（获取第1501页到2500页等待3600秒，获取第2501页到第3000页等待2000秒，以此类推）。

如果还有问题欢迎继续讨论
