### ISSUE TITLE
程序运行出错

### ISSUE THREAD

**Issue by sy917975354** [dataabc/weiboSpider#210]
运行出错的提示：
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\weibo_spider\parser\info_parser.py", line 42, in extract_user_info
    "//div[@class='tip'][2]/text()")[0] == u"学习经历":
IndexError: list index out of range
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\weibo_spider\parser\index_parser.py", line 35, in get_user
    for k, v in user.items():
AttributeError: 'NoneType' object has no attribute 'items'
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\weibo_spider\weiboSpider.py", line 196, in start
    self.get_user_info(user_config["user_uri"])
  File "C:\Program Files\Python37\lib\site-packages\weibo_spider\weiboSpider.py", line 84, in get_user_info
    for k, v in user.items():
AttributeError: 'NoneType' object has no attribute 'items'
Error:  list index out of range
Error:  'NoneType' object has no attribute 'items'
Error:  'NoneType' object has no attribute 'items'

**Comment by dataabc** [comment]
感谢反馈。

应该是速度太快被限制了，限制一段时间会自动解除。可以通过降低速度避免被限。具体修改config.json文件的如下配置：
```
    "random_wait_pages": [1, 5],
    "random_wait_seconds": [6, 10],
    "global_wait": [[1000, 3600], [500, 2000]],    
```
前两行的意思是每爬取1到5页，随机等待6到10秒。可以通过加快暂停频率（减小random_wait_pages内的值）或增加等待时间（加大random_wait_seconds内的值）避免被限制。最后一行的意思是获取1000页微博，一次性等待3600秒；之后获取500页微博一次性等待2000秒。默认只有两个global_wait配置（[1000, 3600]和[500, 2000]），可以添加更多个，也可以自定义。当配置使用完，如默认配置在获取1500（1000+500）页微博后就用完了，之后程序会从第一个配置开始循环使用（获取第1501页到2500页等待3600秒，获取第2501页到第3000页等待2000秒，以此类推）。

如果还有问题，欢迎继续讨论
