### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by Cui-x** [dataabc/weiboSpider#224]
为了更好的解决问题，请认真回答下面的问题。等到问题解决，请及时关闭本issue。<br>

- 问：请您指明哪个版本运行出错（github版/PyPi版/全部）？<br>
答：github版

- 问：您使用的是否是最新的程序（是/否）？<br>
答：是

- 问：爬取任意用户都会运行出错吗（是/否）？<br>
答：没有运行成功

- 问：若只有爬特定微博时才出错，能否提供出错微博的weibo_id或url（非必填）？<br>
答：

- 问：若您已提供出错微博的weibo_id或url，可忽略此内容，否则能否提供出错账号的**user_id**及您配置的**since_date**，方便我们定位出错微博（非必填）？<br>
答：

- 问：如果方便，请您描述出错详情，最好附上错误提示。<br>
答：
(base) E:\Download\weiboSpider-master\weiboSpider>pip install -r requirements.txt
Requirement already satisfied: lxml==4.5.1 in d:\users\000\anaconda3\lib\site-packages (from -r requirements.txt (line 1)) (4.5.1)
Requirement already satisfied: requests==2.23.0 in d:\users\000\anaconda3\lib\site-packages (from -r requirements.txt (line 2)) (2.23.0)
Requirement already satisfied: tqdm==4.46.1 in d:\users\000\anaconda3\lib\site-packages (from -r requirements.txt (line 3)) (4.46.1)
Collecting absl-py==0.9.0
  Downloading absl-py-0.9.0.tar.gz (104 kB)
     |████████████████████████████████| 104 kB 204 kB/s
Requirement already satisfied: idna<3,>=2.5 in d:\users\000\anaconda3\lib\site-packages (from requests==2.23.0->-r requirements.txt (line 2)) (2.8)
Requirement already satisfied: chardet<4,>=3.0.2 in d:\users\000\anaconda3\lib\site-packages (from requests==2.23.0->-r requirements.txt (line 2)) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in d:\users\000\anaconda3\lib\site-packages (from requests==2.23.0->-r requirements.txt (line 2)) (2020.6.20)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in d:\users\000\anaconda3\lib\site-packages (from requests==2.23.0->-r requirements.txt (line 2)) (1.24.1)
Requirement already satisfied: six in d:\users\000\anaconda3\lib\site-packages (from absl-py==0.9.0->-r requirements.txt (line 4)) (1.12.0)
Building wheels for collected packages: absl-py
  Building wheel for absl-py (setup.py) ... done
  Created wheel for absl-py: filename=absl_py-0.9.0-py3-none-any.whl size=121935 sha256=58c884b35b320439eb5689edd7f09b6a9780d283a938f50652529de8d9055dd6
  Stored in directory: c:\users\000\appdata\local\pip\cache\wheels\cc\af\1a\498a24d0730ef484019e007bb9e8cef3ac00311a672c049a3e
Successfully built absl-py
ERROR: Error while checking for conflicts. Please file an issue on pip's issue tracker: https://github.com/pypa/pip/issues/new
Traceback (most recent call last):
  File "D:\Users\000\Anaconda3\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 3021, in _dep_map
    return self.__dep_map
  File "D:\Users\000\Anaconda3\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2815, in __getattr__
    raise AttributeError(attr)
AttributeError: _DistInfoDistribution__dep_map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Users\000\Anaconda3\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 3012, in _parsed_pkg_info
    return self._pkg_info
  File "D:\Users\000\Anaconda3\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2815, in __getattr__
    raise AttributeError(attr)
AttributeError: _pkg_info

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Users\000\Anaconda3\lib\site-packages\pip\_internal\commands\install.py", line 535, in _determine_conflicts
    return check_install_conflicts(to_install)
  File "D:\Users\000\Anaconda3\lib\site-packages\pip\_internal\operations\check.py", line 108, in check_install_conflicts
    package_set, _ = create_package_set_from_installed()
  File "D:\Users\000\Anaconda3\lib\site-packages\pip\_internal\operations\check.py", line 50, in create_package_set_from_installed
    package_set[name] = PackageDetails(dist.version, dist.requires())
  File "D:\Users\000\Anaconda3\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2736, in requires
    dm = self._dep_map
  File "D:\Users\000\Anaconda3\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 3023, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "D:\Users\000\Anaconda3\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 3032, in _compute_dependencies
    for req in self._parsed_pkg_info.get_all('Requires-Dist') or []:
  File "D:\Users\000\Anaconda3\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 3014, in _parsed_pkg_info
    metadata = self.get_metadata(self.PKG_INFO)
  File "D:\Users\000\Anaconda3\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 1420, in get_metadata
    value = self._get(path)
  File "D:\Users\000\Anaconda3\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 1616, in _get
    with open(path, 'rb') as stream:
FileNotFoundError: [Errno 2] No such file or directory: 'd:\\users\\000\\anaconda3\\lib\\site-packages\\absl_py-0.10.0.dist-info\\METADATA'
Installing collected packages: absl-py
  Attempting uninstall: absl-py
    Found existing installation: absl-py 0.10.0
ERROR: Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: 'd:\\users\\000\\anaconda3\\lib\\site-packages\\absl_py-0.10.0.dist-info\\RECORD'

(base) E:\Download\weiboSpider-master\weiboSpider>python3 -m weibo_spider
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1520.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1520.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "E:\Download\weiboSpider-master\weiboSpider\weibo_spider\__main__.py", line 4, in <module>
    from absl import app
ModuleNotFoundError: No module named 'absl'

**Comment by dataabc** [comment]
感谢反馈。

貌似absl没有安装成功，可以试着重新安装absl。

如果还有问题欢迎继续讨论

**Comment by Cui-x** [comment]
谢谢！问题已解决我之前是在pycharm的终端框里输入指令，换在powershell里执行就可以了发自我的iPhone------------------ 原始邮件 ------------------发件人: Chen Lei  <notifications@github.com>发送时间: 2020年9月21日 23:35收件人: dataabc/weiboSpider <weiboSpider@noreply.github.com>抄送: Cui-x <yifancxh@sjtu.edu.cn>, Author <author@noreply.github.com>主题: 回复：[dataabc/weiboSpider] 运行报错 (#224)

感谢反馈。

貌似absl没有安装成功，可以试着重新安装absl。

如果还有问题欢迎继续讨论



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/dataabc/weiboSpider/issues/224#issuecomment-696195695",

"url": "https://github.com/dataabc/weiboSpider/issues/224#issuecomment-696195695",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]
