### ISSUE TITLE
运行出错

### ISSUE THREAD

**Issue by hou5835629** [dataabc/weiboSpider#226]
为了更好的解决问题，请认真回答下面的问题。等到问题解决，请及时关闭本issue。<br>

- 问：请您指明哪个版本运行出错（github版/PyPi版/全部）？<br>
答：github

- 问：您使用的是否是最新的程序（是/否）？<br>
答：是

- 问：爬取任意用户都会运行出错吗（是/否）？<br>
答：是

- 问：若只有爬特定微博时才出错，能否提供出错微博的weibo_id或url（非必填）？<br>
答：

- 问：若您已提供出错微博的weibo_id或url，可忽略此内容，否则能否提供出错账号的**user_id**及您配置的**since_date**，方便我们定位出错微博（非必填）？<br>
答：

- 问：如果方便，请您描述出错详情，最好附上错误提示。<br>
答：
list index out of range
Traceback (most recent call last):
  File "/Users/kristen/weiboSpider/weibo_spider/parser/info_parser.py", line 39, in extract_user_info
    if self.selector.xpath(
IndexError: list index out of range
'NoneType' object has no attribute 'id'
Traceback (most recent call last):
  File "/Users/kristen/weiboSpider/weibo_spider/parser/index_parser.py", line 36, in get_user
    self.user.id = user_id
AttributeError: 'NoneType' object has no attribute 'id'
None
****************************************************************************************************
'NoneType' object has no attribute 'nickname'
Traceback (most recent call last):
  File "/Users/kristen/weiboSpider/weibo_spider/spider.py", line 188, in _get_filepath
    self.user.nickname)
AttributeError: 'NoneType' object has no attribute 'nickname'
expected str, bytes or os.PathLike object, not NoneType
Traceback (most recent call last):
  File "/Users/kristen/weiboSpider/weibo_spider/writer/csv_writer.py", line 25, in __init__
    with open(self.file_path, 'a', encoding='utf-8-sig',
TypeError: expected str, bytes or os.PathLike object, not NoneType
'NoneType' object has no attribute 'nickname'
Traceback (most recent call last):
  File "/Users/kristen/weiboSpider/weibo_spider/spider.py", line 188, in _get_filepath
    self.user.nickname)
AttributeError: 'NoneType' object has no attribute 'nickname'
'NoneType' object has no attribute 'nickname'
Traceback (most recent call last):
  File "/Users/kristen/weiboSpider/weibo_spider/spider.py", line 188, in _get_filepath
    self.user.nickname)
AttributeError: 'NoneType' object has no attribute 'nickname'
'NoneType' object has no attribute 'nickname'
Traceback (most recent call last):
  File "/Users/kristen/weiboSpider/weibo_spider/spider.py", line 188, in _get_filepath
    self.user.nickname)
AttributeError: 'NoneType' object has no attribute 'nickname'
'NoneType' object has no attribute '__dict__'
Traceback (most recent call last):
  File "/Users/kristen/weiboSpider/weibo_spider/spider.py", line 269, in start
    self.write_user(self.user)
  File "/Users/kristen/weiboSpider/weibo_spider/spider.py", line 114, in write_user
    writer.write_user(user)
  File "/Users/kristen/weiboSpider/weibo_spider/writer/txt_writer.py", line 29, in write_user
    [v + '：' + str(self.user.__dict__[k]) for k, v in self.user_desc])
  File "/Users/kristen/weiboSpider/weibo_spider/writer/txt_writer.py", line 29, in <listcomp>
    [v + '：' + str(self.user.__dict__[k]) for k, v in self.user_desc])
AttributeError: 'NoneType' object has no attribute '__dict__'

**Comment by dataabc** [comment]
感谢反馈。

这是爬取速度太快，被暂时限制了，一段时间后限制会自动解除。可以参考[常见问题](https://github.com/dataabc/weiboSpider/blob/master/docs/FAQ.md)的问题2。

如果还有问题欢迎继续讨论。
