### ISSUE TITLE
运行出错

### ISSUE THREAD

**Issue by ChenYuyu1912** [dataabc/weiboSpider#230]
为了更好的解决问题，请认真回答下面的问题。等到问题解决，请及时关闭本issue。<br>

- 问：请您指明哪个版本运行出错（github版/PyPi版/全部）？<br>
答：python 3

- 问：您使用的是否是最新的程序（是/否）？<br>
答：是的，我修改了写入的数据库名称，把weibo库改成了weibo2；还根据您的方法修改了程序来获取特定时间段的最新100条微博。其他并没有修改。

- 问：如果方便，请您描述出错详情，最好附上错误提示。<br>
答：运行后马上出错，错误提示如下：
list index out of range
Traceback (most recent call last):
  File "F:\weibo\weiboSpider\weibo_spider\parser\info_parser.py", line 40, in extract_user_info
    "//div[@class='tip'][2]/text()")[0] == u'学习经历':
IndexError: list index out of range
'NoneType' object has no attribute 'id'
Traceback (most recent call last):
  File "F:\weibo\weiboSpider\weibo_spider\parser\index_parser.py", line 36, in get_user
    self.user.id = user_id
AttributeError: 'NoneType' object has no attribute 'id'
None
****************************************************************************************************
'NoneType' object has no attribute 'nickname'
Traceback (most recent call last):
  File "F:\weibo\weiboSpider\weibo_spider\spider.py", line 188, in _get_filepath
    self.user.nickname)
AttributeError: 'NoneType' object has no attribute 'nickname'
expected str, bytes or os.PathLike object, not NoneType
Traceback (most recent call last):
  File "F:\weibo\weiboSpider\weibo_spider\writer\csv_writer.py", line 26, in __init__
    newline='') as f:
TypeError: expected str, bytes or os.PathLike object, not NoneType
'NoneType' object has no attribute '__dict__'
Traceback (most recent call last):
  File "F:\weibo\weiboSpider\weibo_spider\spider.py", line 269, in start
    self.write_user(self.user)
  File "F:\weibo\weiboSpider\weibo_spider\spider.py", line 114, in write_user
    writer.write_user(user)
  File "F:\weibo\weiboSpider\weibo_spider\writer\mysql_writer.py", line 135, in write_user
    self._mysql_insert('user', [user.__dict__])
AttributeError: 'NoneType' object has no attribute '__dict__'

**Comment by dataabc** [comment]
感谢反馈。

这是因为速度太快了，减速就可以，参考[常见问题](https://github.com/dataabc/weiboSpider/blob/master/docs/FAQ.md)的问题2。

如果还有疑问欢迎继续讨论
