### ISSUE TITLE
程序运行过程中报错raise RuntimeError("cannot join current thread")

### ISSUE THREAD

**Issue by Tesla9527** [dataabc/weiboSpider#235]
为了更好的解决问题，请认真回答下面的问题。等到问题解决，请及时关闭本issue。<br>

- 问：请您指明哪个版本运行出错（github版/PyPi版/全部）？<br>
答：PyPi版

- 问：您使用的是否是最新的程序（是/否）？<br>
答：是

- 问：爬取任意用户都会运行出错吗（是/否）？<br>
答：是

- 问：若只有爬特定微博时才出错，能否提供出错微博的weibo_id或url（非必填）？<br>
答：

- 问：若您已提供出错微博的weibo_id或url，可忽略此内容，否则能否提供出错账号的**user_id**及您配置的**since_date**，方便我们定位出错微博（非必填）？<br>
答：

- 问：如果方便，请您描述出错详情，最好附上错误提示。<br>
答：
共爬取1条原创微博
信息抓取完毕
****************************************************************************************************
Exception ignored in: <function tqdm.__del__ at 0x03F72858>
Traceback (most recent call last):
  File "C:\Users\Tesla Lau\AppData\Local\Programs\Python\Python37-32\lib\site-packages\tqdm\_tqdm.py", line 889, in __del__
    self.close()
  File "C:\Users\Tesla Lau\AppData\Local\Programs\Python\Python37-32\lib\site-packages\tqdm\_tqdm.py", line 1095, in close
    self._decr_instances(self)
  File "C:\Users\Tesla Lau\AppData\Local\Programs\Python\Python37-32\lib\site-packages\tqdm\_tqdm.py", line 454, in _decr_instances
    cls.monitor.exit()
  File "C:\Users\Tesla Lau\AppData\Local\Programs\Python\Python37-32\lib\site-packages\tqdm\_monitor.py", line 52, in exit
    self.join()
  File "C:\Users\Tesla Lau\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 1029, in join
    raise RuntimeError("cannot join current thread")
RuntimeError: cannot join current thread

**Comment by dataabc** [comment]
感谢反馈。

这应该是tqdm的问题，更换tqdm的版本就可以了。

如果还有问题欢迎继续讨论
