### ISSUE TITLE
运行报错-util.py - ERROR

### ISSUE THREAD

**Issue by Alex-Yip** [dataabc/weiboSpider#239]
为了更好的解决问题，请认真回答下面的问题。等到问题解决，请及时关闭本issue。<br>

- 问：请您指明哪个版本运行出错（github版/PyPi版/全部）？<br>
答：GitHub

- 问：您使用的是否是最新的程序（是/否）？<br>
答：是

- 问：爬取任意用户都会运行出错吗（是/否）？<br>
答：是

- 问：若只有爬特定微博时才出错，能否提供出错微博的weibo_id或url（非必填）？<br>
答：

- 问：若您已提供出错微博的weibo_id或url，可忽略此内容，否则能否提供出错账号的**user_id**及您配置的**since_date**，方便我们定位出错微博（非必填）？<br>
答：

- 问：如果方便，请您描述出错详情，最好附上错误提示。<br>
答：
2020-10-11 20:52:37,762 - util.py - ERROR - 'latin-1' codec can't encode character '\u2026' in position 519: ordinal not in range(256)
Traceback (most recent call last):
  File "/Users/eric/Downloads/weiboSpider/weibo_spider/parser/util.py", line 22, in handle_html
    resp = requests.get(url, cookies=cookie)
  File "/Users/eric/anaconda3/lib/python3.7/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/Users/eric/anaconda3/lib/python3.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/eric/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/eric/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/Users/eric/anaconda3/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/Users/eric/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/Users/eric/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/Users/eric/anaconda3/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Users/eric/anaconda3/lib/python3.7/http/client.py", line 1270, in _send_request
    self.putheader(hdr, value)
  File "/Users/eric/anaconda3/lib/python3.7/http/client.py", line 1202, in putheader
    values[i] = one_value.encode('latin-1')
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2026' in position 519: ordinal not in range(256)
2020-10-11 20:52:37,766 - index_parser.py - ERROR - 'NoneType' object has no attribute 'xpath'
Traceback (most recent call last):
  File "/Users/eric/Downloads/weiboSpider/weibo_spider/parser/index_parser.py", line 33, in get_user
    user_id = self._get_user_id()
  File "/Users/eric/Downloads/weiboSpider/weibo_spider/parser/index_parser.py", line 20, in _get_user_id
    url_list = self.selector.xpath("//div[@class='u']//a")
AttributeError: 'NoneType' object has no attribute 'xpath'
2020-10-11 20:52:37,766 - spider.py - INFO - None
2020-10-11 20:52:37,766 - spider.py - INFO - ****************************************************************************************************
2020-10-11 20:52:37,769 - spider.py - ERROR - 'NoneType' object has no attribute 'nickname'
Traceback (most recent call last):
  File "/Users/eric/Downloads/weiboSpider/weibo_spider/spider.py", line 188, in _get_filepath
    self.user.nickname)
AttributeError: 'NoneType' object has no attribute 'nickname'
2020-10-11 20:52:37,769 - csv_writer.py - ERROR - expected str, bytes or os.PathLike object, not NoneType
Traceback (most recent call last):
  File "/Users/eric/Downloads/weiboSpider/weibo_spider/writer/csv_writer.py", line 26, in __init__
    newline='') as f:
TypeError: expected str, bytes or os.PathLike object, not NoneType
2020-10-11 20:52:37,769 - spider.py - ERROR - 'NoneType' object has no attribute 'nickname'
Traceback (most recent call last):
  File "/Users/eric/Downloads/weiboSpider/weibo_spider/spider.py", line 188, in _get_filepath
    self.user.nickname)
AttributeError: 'NoneType' object has no attribute 'nickname'
2020-10-11 20:52:37,771 - spider.py - ERROR - 'NoneType' object has no attribute 'nickname'
Traceback (most recent call last):
  File "/Users/eric/Downloads/weiboSpider/weibo_spider/spider.py", line 188, in _get_filepath
    self.user.nickname)
AttributeError: 'NoneType' object has no attribute 'nickname'
2020-10-11 20:52:37,771 - spider.py - ERROR - 'NoneType' object has no attribute '__dict__'
Traceback (most recent call last):
  File "/Users/eric/Downloads/weiboSpider/weibo_spider/spider.py", line 269, in start
    self.write_user(self.user)
  File "/Users/eric/Downloads/weiboSpider/weibo_spider/spider.py", line 114, in write_user
    writer.write_user(user)
  File "/Users/eric/Downloads/weiboSpider/weibo_spider/writer/txt_writer.py", line 29, in write_user
    [v + '：' + str(self.user.__dict__[k]) for k, v in self.user_desc])
  File "/Users/eric/Downloads/weiboSpider/weibo_spider/writer/txt_writer.py", line 29, in <listcomp>
    [v + '：' + str(self.user.__dict__[k]) for k, v in self.user_desc])
AttributeError: 'NoneType' object has no attribute '__dict__'

**Comment by dataabc** [comment]
感谢反馈。

猜测可能是编码问题或者cookie有问题，网上有个类似的[requests爬虫请求报错](https://www.cnblogs.com/TOM666/p/12874719.html)，不知道是不是这种情况。

如果还有问题欢迎继续讨论。
