### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by sharsunsir** [dataabc/weiboSpider#266]
为了更好的解决问题，请认真回答下面的问题。等到问题解决，请及时关闭本issue。<br>

- 问：请您指明哪个版本运行出错（github版/PyPi版/全部）？<br>
答：

- 问：您使用的是否是最新的程序（是/否）？<br>
答：

- 问：爬取任意用户都会运行出错吗（是/否）？<br>
答：

- 问：若只有爬特定微博时才出错，能否提供出错微博的weibo_id或url（非必填）？<br>
答：

- 问：若您已提供出错微博的weibo_id或url，可忽略此内容，否则能否提供出错账号的**user_id**及您配置的**since_date**，方便我们定位出错微博（非必填）？<br>
答：

- 问：如果方便，请您描述出错详情，最好附上错误提示。<br>
答：
Traceback (most recent call last):
  File "/Users/liushanhui/weiboSpider/weibo_spider/parser/util.py", line 24, in handle_html
    resp = requests.get(url, headers=headers)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/requests/sessions.py", line 516, in request
    prep = self.prepare_request(req)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/requests/sessions.py", line 449, in prepare_request
    p.prepare(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/requests/models.py", line 315, in prepare
    self.prepare_headers(headers)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/requests/models.py", line 449, in prepare_headers
    check_header_validity(header)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/requests/utils.py", line 947, in check_header_validity
    raise InvalidHeader("Invalid return character or leading space in header: %s" % name)
requests.exceptions.InvalidHeader: Invalid return character or leading space in header: Cookie
'NoneType' object has no attribute 'xpath'
Traceback (most recent call last):
  File "/Users/liushanhui/weiboSpider/weibo_spider/parser/index_parser.py", line 33, in get_user
    user_id = self._get_user_id()
  File "/Users/liushanhui/weiboSpider/weibo_spider/parser/index_parser.py", line 20, in _get_user_id
    url_list = self.selector.xpath("//div[@class='u']//a")
AttributeError: 'NoneType' object has no attribute 'xpath'
None
****************************************************************************************************
No module named 'kafka'
Traceback (most recent call last):
  File "/Users/liushanhui/weiboSpider/weibo_spider/spider.py", line 277, in start
    self.initialize_info(user_config)
  File "/Users/liushanhui/weiboSpider/weibo_spider/spider.py", line 215, in initialize_info
    from .writer import CsvWriter
  File "/Users/liushanhui/weiboSpider/weibo_spider/writer/__init__.py", line 7, in <module>
    from .kafka_writer import KafkaWriter
  File "/Users/liushanhui/weiboSpider/weibo_spider/writer/kafka_writer.py", line 4, in <module>
    from kafka import KafkaProducer
ModuleNotFoundError: No module named 'kafka'

**Comment by gankle** [comment]
没有安装 kafka
python -m pip install kafka-python

**Comment by dataabc** [comment]
感谢反馈。

已经修复了，如果还有问题或建议，欢迎继续讨论。
