### ISSUE TITLE
建议下载timeout可配置，感谢！

### ISSUE THREAD

**Issue by chengs2035** [dataabc/weiboSpider#267]
- 问：请说明需要什么新功能。<br>
答：建议下载timeout可配置

- 问：请说明添加该功能的意义。（非必填）<br>
答：可以由用户自行控制超时时间，目前遇到网络缓慢的时候，下载重试多次，还是失败的情况。
具体在日志中表现为：

```

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ya/Projects/Python/weiboSpider/weibo_spider/downloader/downloader.py", line 31, in download_one_file
    downloaded = s.get(url, timeout=(5, 10))
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 685, in send
    r.content
  File "/usr/lib/python3.8/site-packages/requests/models.py", line 829, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  File "/usr/lib/python3.8/site-packages/requests/models.py", line 758, in generate
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='ww4.sinaimg.cn', port=80): Read timed out.
```

我定位到代码是在`weibo_spider/downloader/`下的`downloader.py 的31行`，我现在修改为：`downloaded = s.get(url, timeout=(10, 20))`，情况已经暂时没有出现。

**Comment by dataabc** [comment]
感谢建议。

很不错的建议，我考虑下。因为现在已经有很多配置了，添加新参数会让使用者学习成本增加，但是这个建议确实会提高下载的成功率，有利有弊。目前认为是利大于弊，所以不出意外，这周或下周应该会添加。

感谢建议，如果还有其它建议，欢迎继续讨论。

**Comment by chengs2035** [comment]
> 感谢建议。
> 
> 很不错的建议，我考虑下。因为现在已经有很多配置了，添加新参数会让使用者学习成本增加，但是这个建议确实会提高下载的成功率，有利有弊。目前认为是利大于弊，所以不出意外，这周或下周应该会添加。
> 
> 感谢建议，如果还有其它建议，欢迎继续讨论。

这块可以搞成有配置就用配置的，没配置就默认，属于可选配置，因为我这里网络波动比较大，所以会这样。（我想有代理池的小伙伴应该也会比较大吧）

**Comment by dataabc** [comment]
已添加超时控制。

通过config.json的file_download_timeout参数控制，该参数是列表形式，包含三个数字，第一个代表最多重试数，第二个代表最大连接时间，第三个代表最大读取时间，默认形式：
```
	"file_download_timeout": [5, 5, 10],
```
