### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by gudaocode** [dataabc/weiboSpider#285]
为了更好的解决问题，请认真回答下面的问题。等到问题解决，请及时关闭本issue。<br>

- 问：请您指明哪个版本运行出错（github版/PyPi版/全部）？<br>
答：刚下载了最新的，依旧是这个错误

- 问：您使用的是否是最新的程序（是/否）？<br>
答：是

- 问：爬取任意用户都会运行出错吗（是/否）？<br>
答：

- 问：若只有爬特定微博时才出错，能否提供出错微博的weibo_id或url（非必填）？<br>
答：

- 问：若您已提供出错微博的weibo_id或url，可忽略此内容，否则能否提供出错账号的**user_id**及您配置的**since_date**，方便我们定位出错微博（非必填）？<br>
答：

- 问：如果方便，请您描述出错详情，最好附上错误提示。<br>
答：
2020-12-25 18:19:23,557 - ERROR - page_parser.py[:373] - 'NoneType' object has no attribute 'xpath'
Traceback (most recent call last):
  File "X:\Program Files\GS_Script_Download_WeiBo\weibo_spider\parser\page_parser.py", line 347, in extract_picture_urls
    preview_picture_list = MblogPicAllParser(
  File "X:\Program Files\GS_Script_Download_WeiBo\weibo_spider\parser\mblog_picAll_parser.py", line 12, in extract_preview_picture_list
    return self.selector.xpath('//img/@src')
AttributeError: 'NoneType' object has no attribute 'xpath'
2020-12-25 18:19:23,605 - ERROR - page_parser.py[:373] - 'NoneType' object has no attribute 'xpath'
Traceback (most recent call last):
  File "X:\Program Files\GS_Script_Download_WeiBo\weibo_spider\parser\page_parser.py", line 347, in extract_picture_urls
    preview_picture_list = MblogPicAllParser(
  File "X:\Program Files\GS_Script_Download_WeiBo\weibo_spider\parser\mblog_picAll_parser.py", line 12, in extract_preview_picture_list
    return self.selector.xpath('//img/@src')
AttributeError: 'NoneType' object has no attribute 'xpath'
2020-12-25 18:19:41,444 - ERROR - page_parser.py[:373] - 'NoneType' object has no attribute 'xpath'
Traceback (most recent call last):
  File "X:\Program Files\GS_Script_Download_WeiBo\weibo_spider\parser\page_parser.py", line 347, in extract_picture_urls
    preview_picture_list = MblogPicAllParser(
  File "X:\Program Files\GS_Script_Download_WeiBo\weibo_spider\parser\mblog_picAll_parser.py", line 12, in extract_preview_picture_list
    return self.selector.xpath('//img/@src')
AttributeError: 'NoneType' object has no attribute 'xpath'
2020-12-25 18:19:50,500 - ERROR - page_parser.py[:68] - 'NoneType' object has no attribute 'xpath'
Traceback (most recent call last):
  File "X:\Program Files\GS_Script_Download_WeiBo\weibo_spider\parser\page_parser.py", line 44, in get_one_page
    info = self.selector.xpath("//div[@class='c']")
AttributeError: 'NoneType' object has no attribute 'xpath'
2020-12-25 18:19:50,500 - ERROR - spider.py[:201] - cannot unpack non-iterable NoneType object
Traceback (most recent call last):
  File "X:\Program Files\GS_Script_Download_WeiBo\weibo_spider\spider.py", line 167, in get_weibo_info
    weibos, self.weibo_id_list, to_continue = PageParser(
TypeError: cannot unpack non-iterable NoneType object
2020-12-25 18:20:00,559 - ERROR - index_parser.py[:44] - 'NoneType' object has no attribute 'xpath'
Traceback (most recent call last):
  File "X:\Program Files\GS_Script_Download_WeiBo\weibo_spider\parser\index_parser.py", line 33, in get_user
    user_id = self._get_user_id()
  File "X:\Program Files\GS_Script_Download_WeiBo\weibo_spider\parser\index_parser.py", line 20, in _get_user_id
    url_list = self.selector.xpath("//div[@class='u']//a")
AttributeError: 'NoneType' object has no attribute 'xpath'
2020-12-25 18:20:00,560 - ERROR - spider.py[:222] - 'NoneType' object has no attribute 'nickname'
Traceback (most recent call last):
  File "X:\Program Files\GS_Script_Download_WeiBo\weibo_spider\spider.py", line 206, in _get_filepath
    dir_name = self.user.nickname
AttributeError: 'NoneType' object has no attribute 'nickname'
2020-12-25 18:20:00,560 - ERROR - csv_writer.py[:30] - expected str, bytes or os.PathLike object, not NoneType
Traceback (most recent call last):
  File "X:\Program Files\GS_Script_Download_WeiBo\weibo_spider\writer\csv_writer.py", line 25, in __init__
    with open(self.file_path, 'a', encoding='utf-8-sig',
TypeError: expected str, bytes or os.PathLike object, not NoneType
2020-12-25 18:20:00,560 - ERROR - spider.py[:222] - 'NoneType' object has no attribute 'nickname'
Traceback (most recent call last):
  File "X:\Program Files\GS_Script_Download_WeiBo\weibo_spider\spider.py", line 206, in _get_filepath
    dir_name = self.user.nickname
AttributeError: 'NoneType' object has no attribute 'nickname'
2020-12-25 18:20:00,606 - ERROR - index_parser.py[:56] - 'NoneType' object has no attribute 'xpath'
Traceback (most recent call last):
  File "X:\Program Files\GS_Script_Download_WeiBo\weibo_spider\parser\index_parser.py", line 49, in get_page_num
    if self.selector.xpath("//input[@name='mp']") == []:
AttributeError: 'NoneType' object has no attribute 'xpath'
2020-12-25 18:20:00,607 - ERROR - spider.py[:201] - unsupported operand type(s) for +: 'int' and 'NoneType'
Traceback (most recent call last):
  File "X:\Program Files\GS_Script_Download_WeiBo\weibo_spider\spider.py", line 154, in get_weibo_info
    if self.page_count > 2 and (self.page_count +
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'
2020-12-25 18:20:00,607 - ERROR - spider.py[:322] - 'NoneType' object has no attribute 'nickname'
Traceback (most recent call last):
  File "X:\Program Files\GS_Script_Download_WeiBo\weibo_spider\spider.py", line 318, in start
    self.user.nickname,
AttributeError: 'NoneType' object has no attribute 'nickname'

**Comment by dataabc** [comment]
感谢反馈。

还是速度太快，过一段时间再运行。参考[常见问题](https://github.com/dataabc/weiboSpider/blob/master/docs/FAQ.md)问题2。另外请教下，以前讨论的关闭链接有效果吗？如果有最终是如何实现的？感谢

**Comment by gudaocode** [comment]
没有动任何设置，又启动了一次，虽然记不太清楚，但感觉好像两次报错的位置是一样的呢（或比较接近）
------------------------------已获取赵薇北京影迷会(1757000951)的第67页微博------------------------------
10条微博写入csv文件完毕，保存路径：D:\Desktop\Downloads\Weibo\赵薇北京影迷会\1757000951.csv
即将进行图片下载
Download progress: 100%|███████████████████████████████████████████████████████████████| 10/10 [00:00<00:00, 37.54it/s]
图片下载完毕,保存路径:%|█████████████████████████▌                                      | 4/10 [00:00<00:00, 15.02it/s]
D:\Desktop\Downloads\Weibo\赵薇北京影迷会\img
Progress:   4%|██▋                                                                 | 67/1716 [06:26<2:16:15,  4.96s/it]'NoneType' object has no attribute 'xpath'
Traceback (most recent call last):
  File "X:\Program Files\GS_Script_Download_WeiBo\weibo_spider\parser\page_parser.py", line 44, in get_one_page
    info = self.selector.xpath("//div[@class='c']")
AttributeError: 'NoneType' object has no attribute 'xpath'
Progress:   4%|██▋                                                                 | 67/1716 [06:26<2:38:38,  5.77s/it]
cannot unpack non-iterable NoneType object
Traceback (most recent call last):
  File "X:\Program Files\GS_Script_Download_WeiBo\weibo_spider\spider.py", line 167, in get_weibo_info
    weibos, self.weibo_id_list, to_continue = PageParser(
TypeError: cannot unpack non-iterable NoneType object

会不会是这条博文有点啥问题啊

**Comment by gudaocode** [comment]
对了，之前那个关闭链接的还忘记感谢了，感谢当时的答复，然后，没看懂该怎么弄 汗
不过，后来检测了一下网络连接，当我用py做其他的事情时，您的爬虫确定时断开了链接的，所以，就没有继续研究了

**Comment by dataabc** [comment]
不是博文问题，我能获取到上面的页面，应该是是页面获取到一定数量就限制了。
关闭链接的修改weiboSpider\weibo_spider\parser\util.py的handle_html
修改前
```
         ...
         headers = {'User_Agent': user_agent, 'Cookie': cookie}
         ...
```
修改后
```
         ...
         headers = {'User_Agent': user_agent, 'Cookie': cookie, 'Connection': 'close'}
         ...
```

**Comment by gudaocode** [comment]
感谢！
