### ISSUE TITLE
请问现在这个工具还可以用吗？

### ISSUE THREAD

**Issue by matakk** [dataabc/weiboSpider#29]
我按照方法测试，报告的错误，不知道哪位遇到过

用户名: 登录 - 新
Error:  list index out of range
Traceback (most recent call last):
  File "weiboSpider.py", line 58, in get_user_info
    "//div[@class='tip2']/span[@class='tc']/text()")[0]
IndexError: list index out of range
Error:  list index out of range
Traceback (most recent call last):
  File "weiboSpider.py", line 117, in get_weibo_info
    is_empty = info[0].xpath("div/span[@class='ctt']")
IndexError: list index out of range

**Comment by dataabc** [comment]
可以用，出现上述错误说明cookie没有正确获取，按照README方法获取cookie就可以了

**Comment by matakk** [comment]
谢谢，可以下载了，我加入了随机sleep，后来出现了错误，我恢复了原版，但是反复实验几次后，可以获取到用户名，但是后面的内容失败了，您见过这个错误吗？

X:\v\weibo\weibospider\weiboSpider-master>"F:\DevTools\python\Anaconda2\python.e
xe" weiboSpider.py
Error:  None
Traceback (most recent call last):
  File "weiboSpider.py", line 40, in get_username
    selector = etree.HTML(html)
  File "src\lxml\lxml.etree.pyx", line 3161, in lxml.etree.HTML (src\lxml\lxml.e
tree.c:76137)
  File "src\lxml\parser.pxi", line 1830, in lxml.etree._parseMemoryDocument (src
\lxml\lxml.etree.c:115101)
  File "src\lxml\parser.pxi", line 1718, in lxml.etree._parseDoc (src\lxml\lxml.
etree.c:113781)
  File "src\lxml\parser.pxi", line 1090, in lxml.etree._BaseParser._parseDoc (sr
c\lxml\lxml.etree.c:108226)
  File "src\lxml\parser.pxi", line 584, in lxml.etree._ParserContext._handlePars
eResultDoc (src\lxml\lxml.etree.c:102150)
  File "src\lxml\parser.pxi", line 694, in lxml.etree._handleParseResult (src\lx
ml\lxml.etree.c:103800)
  File "src\lxml\parser.pxi", line 635, in lxml.etree._raiseParseError (src\lxml
\lxml.etree.c:102946)
XMLSyntaxError: None
Error:  None
Traceback (most recent call last):
  File "weiboSpider.py", line 54, in get_user_info
    selector = etree.HTML(html)
  File "src\lxml\lxml.etree.pyx", line 3161, in lxml.etree.HTML (src\lxml\lxml.e
tree.c:76137)
  File "src\lxml\parser.pxi", line 1830, in lxml.etree._parseMemoryDocument (src
\lxml\lxml.etree.c:115101)
  File "src\lxml\parser.pxi", line 1718, in lxml.etree._parseDoc (src\lxml\lxml.
etree.c:113781)
  File "src\lxml\parser.pxi", line 1090, in lxml.etree._BaseParser._parseDoc (sr
c\lxml\lxml.etree.c:108226)
  File "src\lxml\parser.pxi", line 584, in lxml.etree._ParserContext._handlePars
eResultDoc (src\lxml\lxml.etree.c:102150)
  File "src\lxml\parser.pxi", line 694, in lxml.etree._handleParseResult (src\lx
ml\lxml.etree.c:103800)
  File "src\lxml\parser.pxi", line 635, in lxml.etree._raiseParseError (src\lxml
\lxml.etree.c:102946)
XMLSyntaxError: None
Error:  None

**Comment by matakk** [comment]
今天测试了一下又可以了，估计是我测试太频繁了？
我也加入了随机的sleep，测试中。

**Comment by softrime** [comment]
> 谢谢，可以下载了，我加入了随机sleep，后来出现了错误，我恢复了原版，但是反复实验几次后，可以获取到用户名，但是后面的内容失败了，您见过这个错误吗？
> 
> X:\v\weibo\weibospider\weiboSpider-master>"F:\DevTools\python\Anaconda2\python.e
> xe" weiboSpider.py
> Error: None
> Traceback (most recent call last):
> File "weiboSpider.py", line 40, in get_username
> selector = etree.HTML(html)
> File "src\lxml\lxml.etree.pyx", line 3161, in lxml.etree.HTML (src\lxml\lxml.e
> tree.c:76137)
> File "src\lxml\parser.pxi", line 1830, in lxml.etree._parseMemoryDocument (src
> \lxml\lxml.etree.c:115101)
> File "src\lxml\parser.pxi", line 1718, in lxml.etree._parseDoc (src\lxml\lxml.
> etree.c:113781)
> File "src\lxml\parser.pxi", line 1090, in lxml.etree._BaseParser._parseDoc (sr
> c\lxml\lxml.etree.c:108226)
> File "src\lxml\parser.pxi", line 584, in lxml.etree._ParserContext._handlePars
> eResultDoc (src\lxml\lxml.etree.c:102150)
> File "src\lxml\parser.pxi", line 694, in lxml.etree._handleParseResult (src\lx
> ml\lxml.etree.c:103800)
> File "src\lxml\parser.pxi", line 635, in lxml.etree._raiseParseError (src\lxml
> \lxml.etree.c:102946)
> XMLSyntaxError: None
> Error: None
> Traceback (most recent call last):
> File "weiboSpider.py", line 54, in get_user_info
> selector = etree.HTML(html)
> File "src\lxml\lxml.etree.pyx", line 3161, in lxml.etree.HTML (src\lxml\lxml.e
> tree.c:76137)
> File "src\lxml\parser.pxi", line 1830, in lxml.etree._parseMemoryDocument (src
> \lxml\lxml.etree.c:115101)
> File "src\lxml\parser.pxi", line 1718, in lxml.etree._parseDoc (src\lxml\lxml.
> etree.c:113781)
> File "src\lxml\parser.pxi", line 1090, in lxml.etree._BaseParser._parseDoc (sr
> c\lxml\lxml.etree.c:108226)
> File "src\lxml\parser.pxi", line 584, in lxml.etree._ParserContext._handlePars
> eResultDoc (src\lxml\lxml.etree.c:102150)
> File "src\lxml\parser.pxi", line 694, in lxml.etree._handleParseResult (src\lx
> ml\lxml.etree.c:103800)
> File "src\lxml\parser.pxi", line 635, in lxml.etree._raiseParseError (src\lxml
> \lxml.etree.c:102946)
> XMLSyntaxError: None
> Error: None

我也遇到了和你相同的问题，但是我是按照README的方式获取cookie的，你当时是怎么解决的呢

**Comment by softrime** [comment]
我的问题已经解决了，我是在https://weibo.cn/这里面获取的cookie可以通过登录，但是README里面的cookie不行，供参考

**Comment by moonoffifteen** [comment]
> 我的问题已经解决了，我是在[https://weibo.cn/] (https://weibo.cn/)这里面获取的cookie可以通过登录，但是README里面的cookie不行，供参考

是的，我有同样的问题。需要去[https://weibo.cn/] (https://weibo.cn/)获取cookie。

**Comment by V-know** [comment]
2018年12月10号，亲测依然可用！

**Comment by 18912288406** [comment]
用户名: 新浪
('Error: ', IndexError('list index out of range',))
Traceback (most recent call last):
  File "E:\eclipse_0919\workplace_0919\pythonProject003\src\weiboSpider.py", line 57, in get_user_info
    "//div[@class='tip2']/span[@class='tc']/text()")[0]
IndexError: list index out of range
('Error: ', IndexError('list index out of range',))
Traceback (most recent call last):
  File "E:\eclipse_0919\workplace_0919\pythonProject003\src\weiboSpider.py", line 136, in get_weibo_info
    is_empty = info[0].xpath("div/span[@class='ctt']")
IndexError: list index out of range
微博写入文件完毕，保存路径:
E:\eclipse_0919\workplace_0919\pythonProject003\src\weibo\1729370543.txt
信息抓取完毕
===========================================================================
用户名: 新浪
全部微博数: 0
关注数: 0
粉丝数: 0

**Comment by 18912288406** [comment]
难道是我的cooki粘贴错了？

**Comment by zwz453058816** [comment]
请问您用的编译器是什么，我用IDLE显示invalid syntax error，不知道怎么回事，谢谢。

**Comment by dataabc** [comment]
@zwz453058816 说明有语法错误，修改错误行的语法即可，具体哪一行应该有提示
