### ISSUE TITLE
首次运行 $ python3 -m weibo_spider 失败

### ISSUE THREAD

**Issue by leechao199** [dataabc/weiboSpider#292]
macdeMacBook-Pro:~ mac$ cd weiboSpider
macdeMacBook-Pro:weiboSpider mac$ python3 -m weibo_spider
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/mac/weiboSpider/weibo_spider/__main__.py", line 4, in <module>
    from absl import app
ModuleNotFoundError: No module named 'absl'

mac os 版本的python3
首次运行程序
源码安装的用户可以在weiboSpider目录运行如下命令，pip安装的用户可以在任意有写权限的目录运行如下命令
$ python3 -m weibo_spider
就报错 ，错误如上，请问如何解决  
另行安装absl-py后依然无法解决
求解

**Comment by leechao199** [comment]
mac os系统

**Comment by dataabc** [comment]
应该是没有安装absl，安装方法
```
$ pip install absl-py
```
