### ISSUE TITLE
程序在运行过程报错了，具体报错信息如下，好像是溢出了

### ISSUE THREAD

**Issue by fxbyun** [dataabc/weiboSpider#293]
为了更好的解决问题，请认真回答下面的问题。等到问题解决，请及时关闭本issue。<br>

- 问：请您指明哪个版本运行出错（github版/PyPi版/全部）？<br>
答：github版

- 问：您使用的是否是最新的程序（是/否）？<br>
答：是

- 问：爬取任意用户都会运行出错吗（是/否）？<br>
答：否

- 问：若只有爬特定微博时才出错，能否提供出错微博的weibo_id或url（非必填）？<br>
答：不清楚爬到哪个id，没有信息提示

- 问：若您已提供出错微博的weibo_id或url，可忽略此内容，否则能否提供出错账号的**user_id**及您配置的**since_date**，方便我们定位出错微博（非必填）？<br>
答：

- 问：如果方便，请您描述出错详情，最好附上错误提示。<br>
答：****************************************************************************************************
史上最贱信息写入MySQL数据库完毕
****************************************************************************************************
Progress:   0%|          | 0/466 [00:00<?, ?it/s]
------------------------------已获取史上最贱(6112228723)的第1页微博------------------------------
共爬取0条原创微博
信息抓取完毕
****************************************************************************************************
list index out of range
Traceback (most recent call last):
  File "D:\python_work\weiboSpider\weibo_spider\parser\info_parser.py", line 39, in extract_user_info
    if self.selector.xpath(
IndexError: list index out of range
'NoneType' object has no attribute 'id'
Traceback (most recent call last):
  File "D:\python_work\weiboSpider\weibo_spider\parser\index_parser.py", line 36, in get_user
    self.user.id = user_id
AttributeError: 'NoneType' object has no attribute 'id'
None
****************************************************************************************************
'NoneType' object has no attribute 'nickname'
Traceback (most recent call last):
  File "D:\python_work\weiboSpider\weibo_spider\spider.py", line 215, in _get_filepath
    dir_name = self.user.nickname
AttributeError: 'NoneType' object has no attribute 'nickname'
expected str, bytes or os.PathLike object, not NoneType
Traceback (most recent call last):
  File "D:\python_work\weiboSpider\weibo_spider\writer\csv_writer.py", line 25, in __init__
    with open(self.file_path, 'a', encoding='utf-8-sig',
TypeError: expected str, bytes or os.PathLike object, not NoneType
'NoneType' object has no attribute 'nickname'
Traceback (most recent call last):
  File "D:\python_work\weiboSpider\weibo_spider\spider.py", line 215, in _get_filepath
    dir_name = self.user.nickname
AttributeError: 'NoneType' object has no attribute 'nickname'
'NoneType' object has no attribute '__dict__'
Traceback (most recent call last):
  File "D:\python_work\weiboSpider\weibo_spider\spider.py", line 310, in start
    self.write_user(self.user)
  File "D:\python_work\weiboSpider\weibo_spider\spider.py", line 136, in write_user
    writer.write_user(user)
  File "D:\python_work\weiboSpider\weibo_spider\writer\mysql_writer.py", line 135, in write_user
    self._mysql_insert('user', [user.__dict__])
AttributeError: 'NoneType' object has no attribute '__dict__'

Process finished with exit code 0
![image](https://user-images.githubusercontent.com/18391971/106084091-97feb300-6158-11eb-915c-63d36e305c99.png)

**Comment by fxbyun** [comment]
6112228723 史上最贱 2021-01-28 10:31
6457856445 盘就对了 2021-01-27 19:01
![image](https://user-images.githubusercontent.com/18391971/106084255-f592ff80-6158-11eb-9936-ca5391b203b6.png)
user_id_list.txt 的配置截图

**Comment by dataabc** [comment]
感谢反馈。

这是爬取速度太快被暂时限制了，参考[常见问题](https://github.com/dataabc/weiboSpider/blob/master/docs/FAQ.md)的问题2就可以了。

如果还有问题欢迎继续讨论。

**Comment by fxbyun** [comment]
大佬，留个QQ或者微信、微信群的联系方式呗，有些问题咨询交流一下

**Comment by dataabc** [comment]
qq用的比较少，微信回复也不快。有问题直接issue也行，或者通过email也可以，我博客上有我的邮箱，这里就不写了。
