### ISSUE TITLE
爬取多数用户时一切正常，少部分直接显示了“信息抓取完毕”

### ISSUE THREAD

**Issue by rubyflame** [dataabc/weiboSpider#300]
您好，首先感谢您的代码！！我没有使用cookie，爬取多数用户信息时一切正常，只有一位程序直接输出了如下内容：

{}
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
用户信息
'id'
Traceback (most recent call last):
  File "/Users/ruby/PycharmProjects/leetcode/weibo-crawler-master/weibo.py", line 1075, in get_pages
    self.print_user_info()
  File "/Users/ruby/PycharmProjects/leetcode/weibo-crawler-master/weibo.py", line 586, in print_user_info
    logger.info(u'用户id：%s', self.user['id'])
KeyError: 'id'
信息抓取完毕
****************************************************************************************************

我看了一下这位博主应该没有设置什么特殊的权限，不太清楚为什么，期待您的回答！！

**Comment by dataabc** [comment]
感谢反馈。

这是因为有少一部分信息需要cookie才能显示，至于是哪部分可能是随机的，加上cookie就能获取了。

如果还有问题，欢迎继续讨论。
