### ISSUE TITLE
某微博账户无法爬取

### ISSUE THREAD

**Issue by gudaocode** [dataabc/weiboSpider#305]
为了更好的解决问题，请认真回答下面的问题。等到问题解决，请及时关闭本issue。<br>

- 问：请您指明哪个版本运行出错（github版/PyPi版/全部）？<br>
答：

- 问：您使用的是否是最新的程序（是/否）？<br>
答：

- 问：爬取任意用户都会运行出错吗（是/否）？<br>
答：不是

- 问：若只有爬特定微博时才出错，能否提供出错微博的weibo_id或url（非必填）？<br>
答：
只有这个id出错
5609888988

- 问：若您已提供出错微博的weibo_id或url，可忽略此内容，否则能否提供出错账号的**user_id**及您配置的**since_date**，方便我们定位出错微博（非必填）？<br>
答：

- 问：如果方便，请您描述出错详情，最好附上错误提示。<br>
答：
cookie版和非cookie版均出错

本爬虫错误提示：
2021-02-25 22:33:52,420 - spider.py - ERROR - 'NoneType' object has no attribute 'nickname'
Traceback (most recent call last):
  File "X:\***\spider.py", line 174, in get_weibo_info
    self.user.nickname,
AttributeError: 'NoneType' object has no attribute 'nickname'
2021-02-25 22:33:52,421 - spider.py - INFO - 共爬取0条微博
2021-02-25 22:33:52,421 - spider.py - INFO - 信息抓取完毕
2021-02-25 22:33:52,421 - spider.py - INFO - 

非cookie版错误提示：
ERROR - weibo.py[:1107] - 'id'
Traceback (most recent call last):
  File "X:\***\weibo.py", line 1076, in get_pages
    self.print_user_info()
  File "X:\***\weibo.py", line 587, in print_user_info
    logger.info(u'用户id：%s', self.user['id'])
KeyError: 'id'

我的python用的最新3.9.2，不知道是否有影响

**Comment by gudaocode** [comment]
好奇怪，昨天就是不行，今天又没问题了。关闭了，打扰了。
