### ISSUE TITLE
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:852)

### ISSUE THREAD

**Issue by jcq15** [dataabc/weiboSpider#309]
为了更好的解决问题，请认真回答下面的问题。等到问题解决，请及时关闭本issue。<br>

- 问：请您指明哪个版本运行出错（github版/PyPi版/全部）？<br>
答：PyPi版

- 问：您使用的是否是最新的程序（是/否）？<br>
答：是

- 问：爬取任意用户都会运行出错吗（是/否）？<br>
答：是

- 问：若只有爬特定微博时才出错，能否提供出错微博的weibo_id或url（非必填）？<br>
答：

- 问：若您已提供出错微博的weibo_id或url，可忽略此内容，否则能否提供出错账号的**user_id**及您配置的**since_date**，方便我们定位出错微博（非必填）？<br>
答：

- 问：如果方便，请您描述出错详情，最好附上错误提示。<br>
答：

```
HTTPSConnectionPool(host='weibo.cn', port=443): Max retries exceeded with url: /1223178222 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:852)'),))
Traceback (most recent call last):
  File "C:\Users\dalao\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connectionpool.py", line 696, in urlopen
    self._prepare_proxy(conn)
  File "C:\Users\dalao\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connectionpool.py", line 964, in _prepare_proxy
    conn.connect()
  File "C:\Users\dalao\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connection.py", line 359, in connect
    conn = self._connect_tls_proxy(hostname, conn)
  File "C:\Users\dalao\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connection.py", line 502, in _connect_tls_proxy
    ssl_context=ssl_context,
  File "C:\Users\dalao\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\util\ssl_.py", line 432, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "C:\Users\dalao\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\util\ssl_.py", line 474, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "C:\Users\dalao\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "C:\Users\dalao\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 817, in __init__
    self.do_handshake()
  File "C:\Users\dalao\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 1077, in do_handshake
    self._sslobj.do_handshake()
  File "C:\Users\dalao\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:852)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dalao\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "C:\Users\dalao\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "C:\Users\dalao\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\util\retry.py", line 573, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='weibo.cn', port=443): Max retries exceeded with url: /1223178222 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:852)'),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dalao\AppData\Local\Programs\Python\Python36\lib\site-packages\weibo_spider\parser\util.py", line 24, in handle_html
    resp = requests.get(url, headers=headers, verify=False)
  File "C:\Users\dalao\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\dalao\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\dalao\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\dalao\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\dalao\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='weibo.cn', port=443): Max retries exceeded with url: /1223178222 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:852)'),))
'NoneType' object has no attribute 'xpath'
Traceback (most recent call last):
  File "C:\Users\dalao\AppData\Local\Programs\Python\Python36\lib\site-packages\weibo_spider\parser\index_parser.py", line 33, in get_user
    user_id = self._get_user_id()
  File "C:\Users\dalao\AppData\Local\Programs\Python\Python36\lib\site-packages\weibo_spider\parser\index_parser.py", line 20, in _get_user_id
    url_list = self.selector.xpath("//div[@class='u']//a")
AttributeError: 'NoneType' object has no attribute 'xpath'
None
****************************************************************************************************
'NoneType' object has no attribute 'nickname'
Traceback (most recent call last):
  File "C:\Users\dalao\AppData\Local\Programs\Python\Python36\lib\site-packages\weibo_spider\spider.py", line 215, in _get_filepath
    dir_name = self.user.nickname
AttributeError: 'NoneType' object has no attribute 'nickname'
expected str, bytes or os.PathLike object, not NoneType
Traceback (most recent call last):
  File "C:\Users\dalao\AppData\Local\Programs\Python\Python36\lib\site-packages\weibo_spider\writer\csv_writer.py", line 26, in __init__
    newline='') as f:
TypeError: expected str, bytes or os.PathLike object, not NoneType
'NoneType' object has no attribute 'nickname'
Traceback (most recent call last):
  File "C:\Users\dalao\AppData\Local\Programs\Python\Python36\lib\site-packages\weibo_spider\spider.py", line 215, in _get_filepath
    dir_name = self.user.nickname
AttributeError: 'NoneType' object has no attribute 'nickname'
'NoneType' object has no attribute '__dict__'
Traceback (most recent call last):
  File "C:\Users\dalao\AppData\Local\Programs\Python\Python36\lib\site-packages\weibo_spider\spider.py", line 297, in get_one_user
    self.write_user(self.user)
  File "C:\Users\dalao\AppData\Local\Programs\Python\Python36\lib\site-packages\weibo_spider\spider.py", line 136, in write_user
    writer.write_user(user)
  File "C:\Users\dalao\AppData\Local\Programs\Python\Python36\lib\site-packages\weibo_spider\writer\txt_writer.py", line 29, in write_user
    [v + '：' + str(self.user.__dict__[k]) for k, v in self.user_desc])
  File "C:\Users\dalao\AppData\Local\Programs\Python\Python36\lib\site-packages\weibo_spider\writer\txt_writer.py", line 29, in <listcomp>
    [v + '：' + str(self.user.__dict__[k]) for k, v in self.user_desc])
AttributeError: 'NoneType' object has no attribute '__dict__'
HTTPSConnectionPool(host='weibo.cn', port=443): Max retries exceeded with url: /1669879400 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:852)'),))
Traceback (most recent call last):
  File "C:\Users\dalao\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connectionpool.py", line 696, in urlopen
    self._prepare_proxy(conn)
  File "C:\Users\dalao\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connectionpool.py", line 964, in _prepare_proxy
    conn.connect()
  File "C:\Users\dalao\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connection.py", line 359, in connect
    conn = self._connect_tls_proxy(hostname, conn)
  File "C:\Users\dalao\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connection.py", line 502, in _connect_tls_proxy
    ssl_context=ssl_context,
  File "C:\Users\dalao\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\util\ssl_.py", line 432, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "C:\Users\dalao\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\util\ssl_.py", line 474, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "C:\Users\dalao\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "C:\Users\dalao\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 817, in __init__
    self.do_handshake()
  File "C:\Users\dalao\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 1077, in do_handshake
    self._sslobj.do_handshake()
  File "C:\Users\dalao\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:852)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dalao\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "C:\Users\dalao\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "C:\Users\dalao\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\util\retry.py", line 573, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='weibo.cn', port=443): Max retries exceeded with url: /1669879400 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:852)'),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dalao\AppData\Local\Programs\Python\Python36\lib\site-packages\weibo_spider\parser\util.py", line 24, in handle_html
    resp = requests.get(url, headers=headers, verify=False)
  File "C:\Users\dalao\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\dalao\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\dalao\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\dalao\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\dalao\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='weibo.cn', port=443): Max retries exceeded with url: /1669879400 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:852)'),))
'NoneType' object has no attribute 'xpath'
Traceback (most recent call last):
  File "C:\Users\dalao\AppData\Local\Programs\Python\Python36\lib\site-packages\weibo_spider\parser\index_parser.py", line 33, in get_user
    user_id = self._get_user_id()
  File "C:\Users\dalao\AppData\Local\Programs\Python\Python36\lib\site-packages\weibo_spider\parser\index_parser.py", line 20, in _get_user_id
    url_list = self.selector.xpath("//div[@class='u']//a")
AttributeError: 'NoneType' object has no attribute 'xpath'
None
****************************************************************************************************
'NoneType' object has no attribute 'nickname'
Traceback (most recent call last):
  File "C:\Users\dalao\AppData\Local\Programs\Python\Python36\lib\site-packages\weibo_spider\spider.py", line 215, in _get_filepath
    dir_name = self.user.nickname
AttributeError: 'NoneType' object has no attribute 'nickname'
expected str, bytes or os.PathLike object, not NoneType
Traceback (most recent call last):
  File "C:\Users\dalao\AppData\Local\Programs\Python\Python36\lib\site-packages\weibo_spider\writer\csv_writer.py", line 26, in __init__
    newline='') as f:
TypeError: expected str, bytes or os.PathLike object, not NoneType
'NoneType' object has no attribute 'nickname'
Traceback (most recent call last):
  File "C:\Users\dalao\AppData\Local\Programs\Python\Python36\lib\site-packages\weibo_spider\spider.py", line 215, in _get_filepath
    dir_name = self.user.nickname
AttributeError: 'NoneType' object has no attribute 'nickname'
'NoneType' object has no attribute '__dict__'
Traceback (most recent call last):
  File "C:\Users\dalao\AppData\Local\Programs\Python\Python36\lib\site-packages\weibo_spider\spider.py", line 297, in get_one_user
    self.write_user(self.user)
  File "C:\Users\dalao\AppData\Local\Programs\Python\Python36\lib\site-packages\weibo_spider\spider.py", line 136, in write_user
    writer.write_user(user)
  File "C:\Users\dalao\AppData\Local\Programs\Python\Python36\lib\site-packages\weibo_spider\writer\txt_writer.py", line 29, in write_user
    [v + '：' + str(self.user.__dict__[k]) for k, v in self.user_desc])
  File "C:\Users\dalao\AppData\Local\Programs\Python\Python36\lib\site-packages\weibo_spider\writer\txt_writer.py", line 29, in <listcomp>
    [v + '：' + str(self.user.__dict__[k]) for k, v in self.user_desc])
AttributeError: 'NoneType' object has no attribute '__dict__'
```

**Comment by jcq15** [comment]
我已经按照[这里](https://github.com/dataabc/weiboSpider/issues/308#issuecomment-788876137)的方法添加了 `verify=False`，但仍然是上面的错误。

**Comment by dataabc** [comment]
安装certifi、cryptography、pyOpenSSL依赖包了吗，或者是不是修改错文件了？

**Comment by jcq15** [comment]
感谢回复，我装依赖包的时候出现了错误，但我使用另一个项目 https://github.com/dataabc/weibo-crawler 运行成功了~
