### ISSUE TITLE
爬到200页左右就停止爬取，微博内容爬取不全

### ISSUE THREAD

**Issue by baelenz1** [dataabc/weiboSpider#310]
**Progress:  24%|██▍       | 200/821** [1:09:37<3:36:11, 20.89s/it]微博爬取完成，共爬取1986条微博
信息抓取完毕
****************************************************************************************************
您好，这几天用了您更新的版本爬了好几位博主的微博（博主微博数都超过五千条，爬的原创加转发，用户也没有设置半年可见），通过spyder输出结果（如上）&对照抓取的数据和原博主微博基本确定 几位博主的微博爬到200页就停止抓取了，这些博主更早期的微博内容就无法爬取到。

config.json里尝试了一下"start_page"=201，结果也爬不到内容，“
Progress:   0%|          | 0/621 [00:00<?, ?it/s]

微博爬取完成，共爬取0条微博
信息抓取完毕”

想请教一下怎么才能爬取完整。

**Comment by dataabc** [comment]
感谢反馈。能否提供错误的id，方便调试。

**Comment by baelenz1** [comment]
-----Original Message-----

**Comment by dataabc** [comment]
?

**Comment by dataabc** [comment]
你用的应该是免cookie版，如果不写cookie，最多200页，写了可以获得全部。

**Comment by baelenz1** [comment]
用了带cookie版后，

**1. 原创视频和转发视频大概爬到2017年7.8月就无法保存了**（
如，E:\E-weibo-crawler-master\weibo\### 博主名\img\原创微博图片
即将进行原创微博视频下载

Download progress:   0%|          | 0/199 [00:00<?, ?it/s]
Download progress: 100%|██████████| 199/199 [00:00<00:00, 66821.43it/s]原创微博视频下载完毕,保存路径:
E:\E-weibo-crawler-master\weibo\芝士焗土豆丶\video\原创微博视频）

**2.爬到第501页出现错误：**

即将进行转发微博图片下载

Download progress:   0%|          | 0/199 [00:00<?, ?it/s]
Download progress:   3%|▎         | 6/199 [00:00<00:06, 30.85it/s]
Download progress:   4%|▎         | 7/199 [00:01<00:27,  6.94it/s]
Download progress:   6%|▌         | 11/199 [00:02<00:39,  4.74it/s]
Download progress:   7%|▋         | 13/199 [00:03<00:50,  3.71it/s]
Download progress:   7%|▋         | 14/199 [00:04<01:03,  2.92it/s]
Download progress:   8%|▊         | 15/199 [00:05<01:05,  2.79it/s]
Download progress:  10%|▉         | 19/199 [00:05<00:53,  3.34it/s]
Download progress:  11%|█         | 22/199 [00:06<00:48,  3.65it/s]
Download progress:  12%|█▏        | 24/199 [00:12<01:28,  1.97it/s]
Download progress:  14%|█▎        | 27/199 [00:12<01:21,  2.12it/s]
Download progress:  14%|█▍        | 28/199 [00:16<01:41,  1.69it/s]
Download progress:  19%|█▉        | 38/199 [00:25<01:46,  1.51it/s]
Download progress:  24%|██▍       | 48/199 [00:26<01:22,  1.84it/s]
Download progress:  26%|██▌       | 51/199 [00:26<01:16,  1.93it/s]
Download progress:  27%|██▋       | 53/199 [00:30<01:24,  1.73it/s]
Download progress:  29%|██▉       | 58/199 [00:31<01:15,  1.87it/s]
Download progress:  30%|███       | 60/199 [00:31<01:13,  1.90it/s]Traceback (most recent call last):

  File "<ipython-input-1-74a0541b2284>", line 1, in <module>
    runfile('E:/E-weibo-crawler-master/weibo.py', wdir='E:/E-weibo-crawler-master')

  File "D:\ANACODA64\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "D:\ANACODA64\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "E:/E-weibo-crawler-master/weibo.py", line 1193, in <module>
    main()

  File "E:/E-weibo-crawler-master/weibo.py", line 1187, in main
    wb.start()  # 爬取微博信息

  File "E:/E-weibo-crawler-master/weibo.py", line 1156, in start
    self.get_pages()

  File "E:/E-weibo-crawler-master/weibo.py", line 1089, in get_pages
    self.write_data(wrote_count)

  File "E:/E-weibo-crawler-master/weibo.py", line 1064, in write_data
    self.download_files('img', 'retweet', wrote_count)

  File "E:/E-weibo-crawler-master/weibo.py", line 456, in download_files
    self.handle_download(file_type, file_dir, w.get(key), w)

  File "E:/E-weibo-crawler-master/weibo.py", line 403, in handle_download
    self.download_one_file(url, file_path, file_type, w['id'])

  File "E:/E-weibo-crawler-master/weibo.py", line 371, in download_one_file
    verify=False)

  File "D:\ANACODA64\lib\site-packages\requests\sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)

  File "D:\ANACODA64\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)

  File "D:\ANACODA64\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)

  File "D:\ANACODA64\lib\site-packages\requests\adapters.py", line 440, in send
    timeout=timeout

  File "D:\ANACODA64\lib\site-packages\urllib3\connectionpool.py", line 601, in urlopen
    chunked=chunked)

  File "D:\ANACODA64\lib\site-packages\urllib3\connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()

  File "D:\ANACODA64\lib\http\client.py", line 1331, in getresponse
    response.begin()

  File "D:\ANACODA64\lib\http\client.py", line 297, in begin
    version, status, reason = self._read_status()

  File "D:\ANACODA64\lib\http\client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")

  File "D:\ANACODA64\lib\socket.py", line 586, in readinto
    return self._sock.recv_into(b)

  File "D:\ANACODA64\lib\site-packages\urllib3\contrib\pyopenssl.py", line 292, in recv_into
    rd = util.wait_for_read(self.socket, self.socket.gettimeout())

  File "D:\ANACODA64\lib\site-packages\urllib3\util\wait.py", line 33, in wait_for_read
    return _wait_for_io_events(socks, EVENT_READ, timeout)

  File "D:\ANACODA64\lib\site-packages\urllib3\util\wait.py", line 26, in _wait_for_io_events
    selector.select(timeout) if key[1] & events]

  File "D:\ANACODA64\lib\site-packages\urllib3\util\selectors.py", line 320, in select
    self._writers, timeout)

  File "D:\ANACODA64\lib\site-packages\urllib3\util\selectors.py", line 64, in _syscall_wrapper
    return func(*args, **kwargs)

  File "D:\ANACODA64\lib\site-packages\urllib3\util\selectors.py", line 310, in _select
    return select.select(r, w, [], timeout)

KeyboardInterrupt

**3. 想请问可以设置since_date，可否/如何设置end_date?**
（很多只想要抓取博主早期微博，2015-2017年的，都从2021年开始抓太耗费资源）

感谢

**Comment by dataabc** [comment]
end_date目前无法设置，因为不知道end_date发布的微博位置。就是因为这个原因，才有了start_page，它就是间接实现end_date的，告诉程序从哪页开始，可以设置成end_date发布的页数，只是需要手动查找。

**Comment by baelenz1** [comment]
设定start_page后第2.3个问题解决了 17年及更早的视频还是无法保存下来

**Comment by baelenz1** [comment]
可以下载17年及之前视频了~比对发现还是有少量视频会遗漏(还没找到遗漏规律), 不过问题不大。非常感谢~~

**Comment by schaepher** [comment]
> 可以下载17年及之前视频了~比对发现还是有少量视频会遗漏(还没找到遗漏规律), 不过问题不大。非常感谢~~

请尝试使用最新版，应该能下载全了。如果仍然有遗漏，可以再反馈。

与 issue 主题相关的问题已讨论结束。有其他问题或者需要请单独开一个 issue。
