### ISSUE TITLE
保存mysql数据时出现Bug

### ISSUE THREAD

**Issue by wanglu58** [dataabc/weiboSpider#317]
感谢您申报bug，为了表示感谢，如果bug确实存在，您将出现在本项目的贡献者列表里；如果您不但发现了bug，还提供了很好的解决方案，我们会邀请您以pull request的方式成为本项目的代码贡献者（Contributor）；如果您多次提供很好的pull request，我们将邀请您成为本项目的协助者（Collaborator）。当然，是否提供解决方按都是自愿的。不管是否是真正的bug、是否提供解决方案，我们都感谢您对本项目的帮助。<br>
<br>

- 问：请您指明哪个版本出了bug（github版/PyPi版/全部）？<br>
答：github最新版

- 问：您使用的是否是最新的程序（是/否）？<br>
答：是

- 问：爬取任意用户都会复现此bug吗（是/否）？<br>
答：否

- 问：若只有爬特定微博时才出bug，能否提供出错微博的weibo_id或url（非必填）？<br>
答：

- 问：若您已提供出错微博的weibo_id或url，可忽略此内容，否则能否提供出错账号的**user_id**及您配置的**since_date**，方便我们定位出错微博（非必填）？<br>
答：**user_id**5836072940 有糖的美少女

- 问：如果方便，请您描述bug详情，如果代码报错，最好附上错误提示。<br>
答：BUG是因为mysql批量插入时%s是12个，但是args列表参数给少了一个，第4个元组里只有11个的缘故，还希望作者看看。

2021-03-19 11:35:41,715 - mysql_writer.py - INFO - 打印sql语句
2021-03-19 11:35:41,716 - mysql_writer.py - INFO - INSERT INTO weibo(id, user_id, content, article_url, original_pictures, video_url, publish_place, publish_time, publish_tool, up_num, retweet_num, comment_num) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s) ON
                        DUPLICATE KEY UPDATE id = values(id), user_id = values(user_id), content = values(content), article_url = values(article_url), original_pictures = values(original_pictures), video_url = values(video_url), publish_place = values(publish_place), publish_time = values(publish_time), publish_tool = values(publish_tool), up_num = values(up_num), retweet_num = values(retweet_num), comment_num = values(comment_num)

2021-03-19 11:22:16,876 - mysql_writer.py - INFO - 打印args参数
2021-03-19 11:22:16,876 - mysql_writer.py - INFO - [('K6jY66Djp', '5836072940', '最近化妆的技术变好了 长沙·树木岭 \xa0显示地图\xa0原图\xa0', '', 'http://wx3.sinaimg.cn/large/006mXzaIgy1gokq98ycv8j313y0tz13h.jpg', '无', '无', '2021-03-15 17:40', 'iPhone客户端', 14, 0, 5), ('K4j1ChYeH', '5836072940', '不知道从什么时候开始，我疲于回复各种消息，对于喜欢我的人直接逃避，对于自己的爱好渐渐失去兴趣，感觉好多事情对于我来说渐渐变得没有意义。看起来越来越冷血，不对，是没有那么热情。 \xa0', '', '无', '无', '无', '2021-03-02 11:36', 'nova6 5G自拍大不一样', 5, 0, 8), ('K49uOsxyM', '5836072940', '越长大越不想过生日呢 长沙 \xa0显示地图\xa0原图\xa0', '', 'http://wx3.sinaimg.cn/large/006mXzaIgy1go48lknvhqj30sg0lcq6t.jpg', '无', '长沙', '2021-03-01 11:20', 'nova6 5G自拍大不一样', 10, 0, 4), ('K3jm94kWH', '5836072940', '最近阳光都很好，我很喜欢 有糖的美少女的微博视频 \xa0显示地图\xa0', '', '无', 'http://f.video.weibocdn.com/trOty3Qhlx07KBmkkBVm010412006eHq0E010.mp4?label=mp4_hd&template=480x852.24.0&trans_finger=7c347e6ee1691b93dc7e5726f4ef34b3&Expires=1616127735&ssig=p8LARFUbad&KID=unistore,video', '2021-02-23 22:36', 'iPhone客户端', 8, 0, 5), ('K0xT7DLYA', '5836072940', '红红火火恍恍惚惚，小年啦还是要努力工作🦷 长沙 \xa0显示地图\xa0原图\xa0', '', 'http://wx1.sinaimg.cn/large/006mXzaIgy1gnctef9hgtj30u014016s.jpg', '无', '长沙', '2021-02-05 18:05', 'iPhone客户端', 13, 0, 4), ('JEl3V1ZER', '5836072940', '空有一颗当辣妹的心，没有当辣妹的一张脸 长沙 \xa0显示地图\xa0[组图共2张]\xa0原图\xa0', '', 'http://ww4.sinaimg.cn/large/006mXzaIgy1gmwcjtzu6xj32c0340u08.jpg,http://ww1.sinaimg.cn/large/006mXzaIgy1gmwcjt8lcuj32c03401kx.jpg', '无', '长沙', '2021-01-22 12:13', 'iPhone客户端', 19, 0, 14), ('JAIutxzL8', '5836072940', '笑容逐渐放肆 长沙 \xa0显示地图\xa0[组图共3张]\xa0原图\xa0', '', 'http://ww4.sinaimg.cn/large/006mXzaIgy1gm4t5j0u3nj32c02c0qv5.jpg,http://ww3.sinaimg.cn/large/006mXzaIgy1gm4t5jsdonj32c02c0npd.jpg,http://ww1.sinaimg.cn/large/006mXzaIgy1gm4t5hrecvj30n01x04oo.jpg', '无', '长沙', '2020-12-29 16:31', 'iPhone客户端', 6, 0, 4), ('JAzpPbAke', '5836072940', '这样子好像秋天呀🍁 长沙·树木岭 \xa0显示地图\xa0原图\xa0', '', 'http://wx2.sinaimg.cn/large/006mXzaIgy1gm3p3931dfj3289289qv6.jpg', '无', '长沙·树木岭', '2020-12-28 17:25', 'iPhone客户端', 7, 0, 0), ('JAhJJE9Lc', '5836072940', '分享新鲜事~ 长沙·树木岭 \xa0显示地图\xa0[组图共9张]\xa0原图\xa0', '', 'http://ww2.sinaimg.cn/large/006mXzaIgy1gm1imyk3ffj31400u0n6u.jpg,http://ww2.sinaimg.cn/large/006mXzaIgy1gm1imzaxlkj30xx0u0wm9.jpg,http://ww2.sinaimg.cn/large/006mXzaIgy1gm1imzx014j31400u07ex.jpg,http://ww2.sinaimg.cn/large/006mXzaIgy1gm1in1i57bj30u013ztiq.jpg,http://ww2.sinaimg.cn/large/006mXzaIgy1gm1in2397hj30qo0k0wmn.jpg,http://ww4.sinaimg.cn/large/006mXzaIgy1gm1inqbxboj31400u04ct.jpg,http://ww1.sinaimg.cn/large/006mXzaIgy1gm1in3ym9yj31400u0n6c.jpg,http://ww4.sinaimg.cn/large/006mXzaIgy1gm1in4okt8j30n01frdv8.jpg,http://ww2.sinaimg.cn/large/006mXzaIgy1gm1in5k2orj31400u013p.jpg', '无', '无', '2020-12-26 20:24', 'iPhone客户端', 8, 0, 3), ('Jzd0N3RtU', '5836072940', '冷风吹得就很舒服 长沙·树木岭路口公交站 \xa0显示地图\xa0原图\xa0', '', 'http://wx3.sinaimg.cn/large/006mXzaIgy1gltcggedx4j31sc2dskjd.jpg', '无', '无', '2020-12-19 18:32', 'iPhone客户端', 15, 0, 4)]

2021-03-19 11:35:41,724 - mysql_writer.py - ERROR - not enough arguments for format string
Traceback (most recent call last):
  File "D:\KunQian\WeiboSpider\weibo_spider\writer\mysql_writer.py", line 77, in _mysql_insert
    sql, [tuple(data.values()) for data in data_list])
  File "D:\Envs\weibospider\lib\site-packages\pymysql\cursors.py", line 182, in executemany
    self.rowcount = sum(self.execute(query, arg) for arg in args)
  File "D:\Envs\weibospider\lib\site-packages\pymysql\cursors.py", line 182, in <genexpr>
    self.rowcount = sum(self.execute(query, arg) for arg in args)
  File "D:\Envs\weibospider\lib\site-packages\pymysql\cursors.py", line 146, in execute
    query = self.mogrify(query, args)
  File "D:\Envs\weibospider\lib\site-packages\pymysql\cursors.py", line 125, in mogrify
    query = query % self._escape_args(args, conn)
TypeError: not enough arguments for format string

我把sql和arg都打印了出来，打印出来的args参数列表中第4个元组里只有11个值，但是%s有12个，最终就导致这10个数据都不能插入到数据库中，问题还挺严重的。

**Comment by dataabc** [comment]
感谢反馈。

已经修复了，如果还有建议或问题，欢迎继续讨论，再次感谢

**Comment by wanglu58** [comment]
好的，经过测试没有此Bug了，谢谢！
