### ISSUE TITLE
只能抓取100页的数据

### ISSUE THREAD

**Issue by tonray** [dataabc/weiboSpider#337]
Progress:  32%|█████████████████████████▍                                                      | 100/314 [31:55<1:08:18, 19.15s/it]
'NoneType' object has no attribute 'xpath'
Traceback (most recent call last):
  File "/root/weiboSpider/weibo_spider/spider.py", line 169, in get_weibo_info
    self.user_config, page, self.filter).get_one_page(
  File "/root/weiboSpider/weibo_spider/parser/page_parser.py", line 45, in __init__
    info = self.selector.xpath("//div[@class='c']")
AttributeError: 'NoneType' object has no attribute 'xpath'
共爬取997条原创微博
信息抓取完毕

-------------
运行到32%，100页的位置，就中断了

**Comment by tonray** [comment]
又尝试了下，这次抓的更少了
---------------
Progress:  12%|█████████▌                                                                       | 37/315 [09:12<1:09:13, 14.94s/it]
'NoneType' object has no attribute 'xpath'
Traceback (most recent call last):
  File "/root/weiboSpider/weibo_spider/spider.py", line 169, in get_weibo_info
    self.user_config, page, self.filter).get_one_page(
  File "/root/weiboSpider/weibo_spider/parser/page_parser.py", line 45, in __init__
    info = self.selector.xpath("//div[@class='c']")
AttributeError: 'NoneType' object has no attribute 'xpath'
共爬取371条原创微博
信息抓取完毕

**Comment by dataabc** [comment]
感谢反馈。

应该是速度太快了，参考常见问题修改即可。

**Comment by tonray** [comment]
谢谢
