### ISSUE TITLE
运行程序后出现了另外一个bug

### ISSUE THREAD

**Issue by ZhuningS** [dataabc/weiboSpider#350]
您好，感谢你们开发这款程序🙏
感谢您申报bug，为了表示感谢，如果bug确实存在，您将出现在本项目的贡献者列表里；如果您不但发现了bug，还提供了很好的解决方案，我们会邀请您以pull request的方式成为本项目的代码贡献者（Contributor）；如果您多次提供很好的pull request，我们将邀请您成为本项目的协助者（Collaborator）。当然，是否提供解决方按都是自愿的。不管是否是真正的bug、是否提供解决方案，我们都感谢您对本项目的帮助。

- 问：请您指明哪个版本出了bug（github版/PyPi版/全部）？

答：github版 我的python版本3.8.5

- 问：您使用的是否是最新的程序（是/否）？

答：是

- 问：爬取任意用户都会复现此bug吗（是/否）？

答：是

- 问：若只有爬特定微博时才出bug，能否提供出错微博的weibo_id或url（非必填）？

答：否

- 问：如果方便，请您描述bug详情，如果代码报错，最好附上错误提示。

答：HTTPSConnectionPool(host='weibo.cn', port=443): Max retries exceeded with url: /5030944946 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000000003B4E940>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
Traceback (most recent call last):
  File "C:\Users\Intel\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\Intel\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Users\Intel\AppData\Local\Programs\Python\Python38\lib\socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Intel\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\Intel\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "C:\Users\Intel\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "C:\Users\Intel\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connection.py", line 353, in connect
    conn = self._new_conn()
  File "C:\Users\Intel\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x0000000003B4E940>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Intel\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Users\Intel\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "C:\Users\Intel\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\util\retry.py", line 573, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='weibo.cn', port=443): Max retries exceeded with url: /5030944946 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000000003B4E940>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\weiboSpider-master\weibo_spider\parser\util.py", line 25, in handle_html
    resp = requests.get(url, headers=headers)
  File "C:\Users\Intel\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\Intel\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\Intel\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Intel\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Intel\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='weibo.cn', port=443): Max retries exceeded with url: /5030944946 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000000003B4E940>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
'NoneType' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\weiboSpider-master\weibo_spider\parser\index_parser.py", line 33, in get_user
    user_id = self._get_user_id()
  File "D:\weiboSpider-master\weibo_spider\parser\index_parser.py", line 20, in _get_user_id
    url_list = self.selector.xpath("//div[@class='u']//a")
AttributeError: 'NoneType' object has no attribute 'xpath'
None
****************************************************************************************************
'NoneType' object has no attribute 'nickname'
Traceback (most recent call last):
  File "D:\weiboSpider-master\weibo_spider\spider.py", line 215, in _get_filepath
    dir_name = self.user.nickname
AttributeError: 'NoneType' object has no attribute 'nickname'
expected str, bytes or os.PathLike object, not NoneType
Traceback (most recent call last):
  File "D:\weiboSpider-master\weibo_spider\writer\csv_writer.py", line 25, in __init__
    with open(self.file_path, 'a', encoding='utf-8-sig',
TypeError: expected str, bytes or os.PathLike object, not NoneType
'NoneType' object has no attribute 'nickname'
Traceback (most recent call last):
  File "D:\weiboSpider-master\weibo_spider\spider.py", line 215, in _get_filepath
    dir_name = self.user.nickname
AttributeError: 'NoneType' object has no attribute 'nickname'
'NoneType' object has no attribute 'nickname'
Traceback (most recent call last):
  File "D:\weiboSpider-master\weibo_spider\spider.py", line 215, in _get_filepath
    dir_name = self.user.nickname
AttributeError: 'NoneType' object has no attribute 'nickname'
'NoneType' object has no attribute 'nickname'
Traceback (most recent call last):
  File "D:\weiboSpider-master\weibo_spider\spider.py", line 215, in _get_filepath
    dir_name = self.user.nickname
AttributeError: 'NoneType' object has no attribute 'nickname'
'NoneType' object has no attribute 'nickname'
Traceback (most recent call last):
  File "D:\weiboSpider-master\weibo_spider\spider.py", line 215, in _get_filepath
    dir_name = self.user.nickname
AttributeError: 'NoneType' object has no attribute 'nickname'
'NoneType' object has no attribute '__dict__'
Traceback (most recent call last):
  File "D:\weiboSpider-master\weibo_spider\spider.py", line 302, in get_one_user
    self.write_user(self.user)
  File "D:\weiboSpider-master\weibo_spider\spider.py", line 136, in write_user
    writer.write_user(user)
  File "D:\weiboSpider-master\weibo_spider\writer\txt_writer.py", line 29, in write_user
    [v + '：' + str(self.user.__dict__[k]) for k, v in self.user_desc])
  File "D:\weiboSpider-master\weibo_spider\writer\txt_writer.py", line 29, in <listcomp>
    [v + '：' + str(self.user.__dict__[k]) for k, v in self.user_desc])
AttributeError: 'NoneType' object has no attribute '__dict__'

**Comment by ZhuningS** [comment]
config.json文件中："result_dir_name"的值从0改为1后出现的新bug

**Comment by dataabc** [comment]
感谢反馈。

和 #349 类似，因为result_dir_name等于1时要用到用户昵称，因为被限制了，无法获取，所以出错。如果还有问题，欢迎继续讨论。
