### ISSUE TITLE
自己的微博无法爬取会报错

### ISSUE THREAD

**Issue by yumengbdw** [dataabc/weiboSpider#357]
为了更好的解决问题，请认真回答下面的问题。等到问题解决，请及时关闭本issue。

- 问：请您指明哪个版本运行出错（github版/PyPi版/全部）？

答：github

- 问：您使用的是否是最新的程序（是/否）？

答：是

- 问：爬取任意用户都会运行出错吗（是/否）？

答：只有自己的账户会报错

- 问：若只有爬特定微博时才出错，能否提供出错微博的weibo_id或url（非必填）？

答：自己的

- 问：若您已提供出错微博的weibo_id或url，可忽略此内容，否则能否提供出错账号的**user_id**及您配置的**since_date**，方便我们定位出错微博（非必填）？

答：自己的

- 问：如果方便，请您描述出错详情，最好附上错误提示。

答：爬取自己id报错

自己的微博无法爬取会报错

**Comment by dataabc** [comment]
感谢反馈。

参考[常见问题](https://github.com/dataabc/weiboSpider/blob/master/docs/FAQ.md)问题7，如果还有问题，欢迎继续讨论。

**Comment by shenweiyan** [comment]
参考[常见问题](https://github.com/dataabc/weiboSpider/blob/master/docs/FAQ.md)问题7爬取自己的微博，依然会出现错误，个人用的是 github 的最新版本：
```
list index out of range
Traceback (most recent call last):
  File "/data/weiboSpider/weibo_spider/parser/info_parser.py", line 40, in extract_user_info
    "//div[@class='tip'][2]/text()")[0] == u'学习经历':
IndexError: list index out of range
'NoneType' object has no attribute 'id'
Traceback (most recent call last):
  File "/data/weiboSpider/weibo_spider/parser/index_parser.py", line 36, in get_user
    self.user.id = user_id
AttributeError: 'NoneType' object has no attribute 'id'
None
****************************************************************************************************
'NoneType' object has no attribute 'nickname'
Traceback (most recent call last):
  File "/data/weiboSpider/weibo_spider/spider.py", line 215, in _get_filepath
    dir_name = self.user.nickname
AttributeError: 'NoneType' object has no attribute 'nickname'
expected str, bytes or os.PathLike object, not NoneType
Traceback (most recent call last):
  File "/data/weiboSpider/weibo_spider/writer/csv_writer.py", line 26, in __init__
    newline='') as f:
TypeError: expected str, bytes or os.PathLike object, not NoneType
'NoneType' object has no attribute 'nickname'
Traceback (most recent call last):
  File "/data/weiboSpider/weibo_spider/spider.py", line 215, in _get_filepath
    dir_name = self.user.nickname
AttributeError: 'NoneType' object has no attribute 'nickname'
'NoneType' object has no attribute 'nickname'
Traceback (most recent call last):
  File "/data/weiboSpider/weibo_spider/spider.py", line 215, in _get_filepath
    dir_name = self.user.nickname
AttributeError: 'NoneType' object has no attribute 'nickname'
'NoneType' object has no attribute 'nickname'
Traceback (most recent call last):
  File "/data/weiboSpider/weibo_spider/spider.py", line 215, in _get_filepath
    dir_name = self.user.nickname
AttributeError: 'NoneType' object has no attribute 'nickname'
'NoneType' object has no attribute '__dict__'
Traceback (most recent call last):
  File "/data/weiboSpider/weibo_spider/spider.py", line 302, in get_one_user
    self.write_user(self.user)
  File "/data/weiboSpider/weibo_spider/spider.py", line 136, in write_user
    writer.write_user(user)
  File "/data/weiboSpider/weibo_spider/writer/txt_writer.py", line 29, in write_user
    [v + '：' + str(self.user.__dict__[k]) for k, v in self.user_desc])
  File "/data/weiboSpider/weibo_spider/writer/txt_writer.py", line 29, in <listcomp>
    [v + '：' + str(self.user.__dict__[k]) for k, v in self.user_desc])
AttributeError: 'NoneType' object has no attribute '__dict__'
```

**Comment by dataabc** [comment]
@shenweiyan 感谢反馈。NoneType相关的错误一般是被暂时限制了，限制一段时间会自动解除，参考[常见问题](https://github.com/dataabc/weiboSpider/blob/master/docs/FAQ.md)问题2。
