### ISSUE TITLE
运行提示：KeyError: 'random_wait_seconds'

### ISSUE THREAD

**Issue by ziguiway** [dataabc/weiboSpider#380]
为了更好的解决问题，请认真回答下面的问题。等到问题解决，请及时关闭本issue。

- 问：请您指明哪个版本运行出错（github版/PyPi版/全部）？

答：github版

- 问：您使用的是否是最新的程序（是/否）？

答：是

- 问：爬取任意用户都会运行出错吗（是/否）？

答：是

- 问：若只有爬特定微博时才出错，能否提供出错微博的weibo_id或url（非必填）？

答：

- 问：若您已提供出错微博的weibo_id或url，可忽略此内容，否则能否提供出错账号的**user_id**及您配置的**since_date**，方便我们定位出错微博（非必填）？

答：

- 问：如果方便，请您描述出错详情，最好附上错误提示。

答：C:/Users/郑爽/AppData/Local/Programs/Python/Python36/Lib/site-packages/weibo_spider/__main__.py
'random_wait_seconds'
Traceback (most recent call last):
  File "C:\Users\郑爽\AppData\Local\Programs\Python\Python36\lib\site-packages\weibo_spider\spider.py", line 380, in main
    config_util.validate_config(config)
  File "C:\Users\郑爽\AppData\Local\Programs\Python\Python36\lib\site-packages\weibo_spider\config_util.py", line 58, in validate_config
    random_wait_seconds = config['random_wait_seconds']
KeyError: 'random_wait_seconds'

**Comment by dataabc** [comment]
感谢反馈。是不是你的config.json没有random_wait_seconds，获取最新的config.json就可以了。
