### ISSUE TITLE
程序爬资料失败，换账号cookies和IP也解决不了，修改配置文件也是不行

### ISSUE THREAD

**Issue by Ansifa** [dataabc/weiboSpider#387]
应该是今天才开始失效的，换了多次都没解决问题。

- 问：请您指明哪个版本出了bug（github版/PyPi版/全部）？

答：Win10/11，py3.9.0，pip -u更新的最新版，或者github下载的最新版都不行

- 问：您使用的是否是最新的程序（是/否）？

答：是

- 问：爬取任意用户都会复现此bug吗（是/否）？

答：是，并且爬取的所有账户都同款报错。（下面星号围绕部分不断循环）

- 问：若只有爬特定微博时才出bug，能否提供出错微博的weibo_id或url（非必填）？

答：

- 问：若您已提供出错微博的weibo_id或url，可忽略此内容，否则能否提供出错账号的**user_id**及您配置的**since_date**，方便我们定位出错微博（非必填）？

答：

- 问：如果方便，请您描述bug详情，如果代码报错，最好附上错误提示。

答：
```

invalid literal for int() with base 10: '1533.6万'
Traceback (most recent call last):
  File "C:\Users\Ansifa\AppData\Local\Programs\Python\Python39\lib\site-packages\weibo_spider\parser\index_parser.py", line 41, in get_user
    self.user.followers = int(user_info[2][3:-1])
ValueError: invalid literal for int() with base 10: '1533.6万'
None
****************************************************************************************************
'NoneType' object has no attribute 'nickname'
Traceback (most recent call last):
  File "C:\Users\Ansifa\AppData\Local\Programs\Python\Python39\lib\site-packages\weibo_spider\spider.py", line 226, in _get_filepath
    dir_name = self.user.nickname
AttributeError: 'NoneType' object has no attribute 'nickname'
expected str, bytes or os.PathLike object, not NoneType
Traceback (most recent call last):
  File "C:\Users\Ansifa\AppData\Local\Programs\Python\Python39\lib\site-packages\weibo_spider\writer\csv_writer.py", line 25, in __init__
    with open(self.file_path, 'a', encoding='utf-8-sig',
TypeError: expected str, bytes or os.PathLike object, not NoneType
'NoneType' object has no attribute 'nickname'
Traceback (most recent call last):
  File "C:\Users\Ansifa\AppData\Local\Programs\Python\Python39\lib\site-packages\weibo_spider\spider.py", line 226, in _get_filepath
    dir_name = self.user.nickname
AttributeError: 'NoneType' object has no attribute 'nickname'
'NoneType' object has no attribute 'nickname'
Traceback (most recent call last):
  File "C:\Users\Ansifa\AppData\Local\Programs\Python\Python39\lib\site-packages\weibo_spider\spider.py", line 226, in _get_filepath
    dir_name = self.user.nickname
AttributeError: 'NoneType' object has no attribute 'nickname'
****************************************************************************************************
```

**Comment by dataabc** [comment]
感谢反馈。问题已经修复了，如果发现其它问题或有其它疑问，欢迎继续讨论，再次感谢。
