### ISSUE TITLE
Error:  list index out of range

### ISSUE THREAD

**Issue by slimwang** [dataabc/weiboSpider#39]
```python
Error:  list index out of range
Traceback (most recent call last):
  File "/weiboSpider/weiboSpider.py", line 123, in get_weibo_content
    weibo_content = str_t[0].xpath("string(.)").replace(u"\u200b", "").encode(
IndexError: list index out of range
Error:  list index out of range
Traceback (most recent call last):
  File "/weiboSpider/weiboSpider.py", line 150, in get_weibo_place
    div_first = info.xpath("div")[0]
IndexError: list index out of range
Error:  list index out of range
Traceback (most recent call last):
  File "/weiboSpider/weiboSpider.py", line 177, in get_publish_time
    str_time = str_time[0].xpath("string(.)").encode(
IndexError: list index out of range
Error:  list index out of range
Traceback (most recent call last):
  File "/weiboSpider/weiboSpider.py", line 210, in get_publish_tool
    str_time = str_time[0].xpath("string(.)").encode(
IndexError: list index out of range
```

主要问题出在这句话上:
```python
str_footer = info[0].xpath("div")[-1]
IndexError: list index out of range
```

大概需要先判断一下 info 存不存在
写成这个样子:
```python
str_footer = info[0].xpath("div")[-1] if info else ''
```

**Comment by dataabc** [comment]
能否提供出错的微博id，调试下，谢谢

**Comment by slimwang** [comment]
5674301106

**Comment by dataabc** [comment]
测试了上述账号，爬了9000多条微博，没有出现错误。你的账号出现"list index out of range"可能是因为账号爬取太频繁被限制了，如果是这个问题，限制下爬取速度(如每爬几页sleep一段时间再爬)就可以了
