### ISSUE TITLE
用user_id_list就报错，在config中设置user id就一切正常

### ISSUE THREAD

**Issue by Mordiggian** [dataabc/weiboSpider#393]
为了更好的解决问题，请认真回答下面的问题。等到问题解决，请及时关闭本issue。

- 问：请您指明哪个版本运行出错（github版/PyPi版/全部）？

答：github

- 问：您使用的是否是最新的程序（是/否）？

答：是

- 问：爬取任意用户都会运行出错吗（是/否）？

答：是

- 问：若只有爬特定微博时才出错，能否提供出错微博的weibo_id或url（非必填）？

答：否

- 问：若您已提供出错微博的weibo_id或url，可忽略此内容，否则能否提供出错账号的**user_id**及您配置的**since_date**，方便我们定位出错微博（非必填）？

答：

- 问：如果方便，请您描述出错详情，最好附上错误提示。

答：

list index out of range
Traceback (most recent call last):
  File "/Users/Moordiig/.pyenv/versions/my-env/lib/python3.9/site-packages/weibo_spider/parser/info_parser.py", line 39, in extract_user_info
    if self.selector.xpath(
IndexError: list index out of range
'NoneType' object has no attribute 'id'
Traceback (most recent call last):
  File "/Users/Moordiig/.pyenv/versions/my-env/lib/python3.9/site-packages/weibo_spider/parser/index_parser.py", line 36, in get_user
    self.user.id = user_id
AttributeError: 'NoneType' object has no attribute 'id'
None
****************************************************************************************************
'NoneType' object has no attribute 'nickname'
Traceback (most recent call last):
  File "/Users/Moordiig/.pyenv/versions/my-env/lib/python3.9/site-packages/weibo_spider/spider.py", line 226, in _get_filepath
    dir_name = self.user.nickname
AttributeError: 'NoneType' object has no attribute 'nickname'
expected str, bytes or os.PathLike object, not NoneType
Traceback (most recent call last):
  File "/Users/Moordiig/.pyenv/versions/my-env/lib/python3.9/site-packages/weibo_spider/writer/csv_writer.py", line 25, in __init__
    with open(self.file_path, 'a', encoding='utf-8-sig',
TypeError: expected str, bytes or os.PathLike object, not NoneType
'NoneType' object has no attribute 'nickname'
Traceback (most recent call last):
  File "/Users/Moordiig/.pyenv/versions/my-env/lib/python3.9/site-packages/weibo_spider/spider.py", line 226, in _get_filepath
    dir_name = self.user.nickname
AttributeError: 'NoneType' object has no attribute 'nickname'
'NoneType' object has no attribute 'nickname'
Traceback (most recent call last):
  File "/Users/Moordiig/.pyenv/versions/my-env/lib/python3.9/site-packages/weibo_spider/spider.py", line 226, in _get_filepath
    dir_name = self.user.nickname
AttributeError: 'NoneType' object has no attribute 'nickname'
'NoneType' object has no attribute 'nickname'
Traceback (most recent call last):
  File "/Users/Moordiig/.pyenv/versions/my-env/lib/python3.9/site-packages/weibo_spider/spider.py", line 226, in _get_filepath
    dir_name = self.user.nickname
AttributeError: 'NoneType' object has no attribute 'nickname'
'NoneType' object has no attribute 'nickname'
Traceback (most recent call last):
  File "/Users/Moordiig/.pyenv/versions/my-env/lib/python3.9/site-packages/weibo_spider/spider.py", line 226, in _get_filepath
    dir_name = self.user.nickname
AttributeError: 'NoneType' object has no attribute 'nickname'
'NoneType' object has no attribute '__dict__'
Traceback (most recent call last):
  File "/Users/Moordiig/.pyenv/versions/my-env/lib/python3.9/site-packages/weibo_spider/spider.py", line 313, in get_one_user
    self.write_user(self.user)
  File "/Users/Moordiig/.pyenv/versions/my-env/lib/python3.9/site-packages/weibo_spider/spider.py", line 137, in write_user
    writer.write_user(user)
  File "/Users/Moordiig/.pyenv/versions/my-env/lib/python3.9/site-packages/weibo_spider/writer/txt_writer.py", line 29, in write_user
    [v + '：' + str(self.user.__dict__[k]) for k, v in self.user_desc])
  File "/Users/Moordiig/.pyenv/versions/my-env/lib/python3.9/site-packages/weibo_spider/writer/txt_writer.py", line 29, in <listcomp>
    [v + '：' + str(self.user.__dict__[k]) for k, v in self.user_desc])
AttributeError: 'NoneType' object has no attribute '__dict__'
(my-env)  Ray@Mac  ~/desktop/weibospider  python3 -m weibo_spider --config_path="config.json"
list index out of range
Traceback (most recent call last):
  File "/Users/Moordiig/.pyenv/versions/my-env/lib/python3.9/site-packages/weibo_spider/parser/info_parser.py", line 39, in extract_user_info
    if self.selector.xpath(
IndexError: list index out of range
'NoneType' object has no attribute 'id'
Traceback (most recent call last):
  File "/Users/Moordiig/.pyenv/versions/my-env/lib/python3.9/site-packages/weibo_spider/parser/index_parser.py", line 36, in get_user
    self.user.id = user_id
AttributeError: 'NoneType' object has no attribute 'id'
None
****************************************************************************************************
'NoneType' object has no attribute 'nickname'
Traceback (most recent call last):
  File "/Users/Moordiig/.pyenv/versions/my-env/lib/python3.9/site-packages/weibo_spider/spider.py", line 226, in _get_filepath
    dir_name = self.user.nickname
AttributeError: 'NoneType' object has no attribute 'nickname'
expected str, bytes or os.PathLike object, not NoneType
Traceback (most recent call last):
  File "/Users/Moordiig/.pyenv/versions/my-env/lib/python3.9/site-packages/weibo_spider/writer/csv_writer.py", line 25, in __init__
    with open(self.file_path, 'a', encoding='utf-8-sig',
TypeError: expected str, bytes or os.PathLike object, not NoneType
'NoneType' object has no attribute 'nickname'
Traceback (most recent call last):
  File "/Users/Moordiig/.pyenv/versions/my-env/lib/python3.9/site-packages/weibo_spider/spider.py", line 226, in _get_filepath
    dir_name = self.user.nickname
AttributeError: 'NoneType' object has no attribute 'nickname'
'NoneType' object has no attribute 'nickname'
Traceback (most recent call last):
  File "/Users/Moordiig/.pyenv/versions/my-env/lib/python3.9/site-packages/weibo_spider/spider.py", line 226, in _get_filepath
    dir_name = self.user.nickname
AttributeError: 'NoneType' object has no attribute 'nickname'
'NoneType' object has no attribute 'nickname'
Traceback (most recent call last):
  File "/Users/Moordiig/.pyenv/versions/my-env/lib/python3.9/site-packages/weibo_spider/spider.py", line 226, in _get_filepath
    dir_name = self.user.nickname
AttributeError: 'NoneType' object has no attribute 'nickname'
'NoneType' object has no attribute 'nickname'
Traceback (most recent call last):
  File "/Users/Moordiig/.pyenv/versions/my-env/lib/python3.9/site-packages/weibo_spider/spider.py", line 226, in _get_filepath
    dir_name = self.user.nickname
AttributeError: 'NoneType' object has no attribute 'nickname'
'NoneType' object has no attribute '__dict__'
Traceback (most recent call last):
  File "/Users/Moordiig/.pyenv/versions/my-env/lib/python3.9/site-packages/weibo_spider/spider.py", line 313, in get_one_user
    self.write_user(self.user)
  File "/Users/Moordiig/.pyenv/versions/my-env/lib/python3.9/site-packages/weibo_spider/spider.py", line 137, in write_user
    writer.write_user(user)
  File "/Users/Moordiig/.pyenv/versions/my-env/lib/python3.9/site-packages/weibo_spider/writer/txt_writer.py", line 29, in write_user
    [v + '：' + str(self.user.__dict__[k]) for k, v in self.user_desc])
  File "/Users/Moordiig/.pyenv/versions/my-env/lib/python3.9/site-packages/weibo_spider/writer/txt_writer.py", line 29, in <listcomp>
    [v + '：' + str(self.user.__dict__[k]) for k, v in self.user_desc])
AttributeError: 'NoneType' object has no attribute '__dict__'

**Comment by dataabc** [comment]
感谢反馈。这个问题看起来像[常见问题](https://github.com/dataabc/weiboSpider/blob/master/docs/FAQ.md)的问题2。但是如果这样不管如何输入user_id都会报错。你用这两种方式在短时间测试过吗？按理说，如果第一种方式报错，第二种也会报错。

**Comment by Mordiggian** [comment]
是的，我之前一直在自己的vps上使用user_id_list.txt配合crontab有快一年，然后从九月份一直报NoneType类的错，之前一直没空看，然后今天我试了在vps上重新下载新的再试依然不行。这个是我用自己电脑试的，自己电脑上在user_id_list上写id就正常爬取，用txt就不行

**Comment by dataabc** [comment]
我测试了下，没问题的。是不是修改过代码或者同时安装了pypi版？
