### ISSUE TITLE
已成功运行一次，再运行一次时提示cookie错误或已过期

### ISSUE THREAD

**Issue by banlangen1111** [dataabc/weiboSpider#408]
为了更好的解决问题，请认真回答下面的问题。等到问题解决，请及时关闭本issue。

- 问：请您指明哪个版本运行出错（github版/PyPi版/全部）？

答：github

- 问：您使用的是否是最新的程序（是/否）？

答：是

- 问：爬取任意用户都会运行出错吗（是/否）？

答：是

- 问：若只有爬特定微博时才出错，能否提供出错微博的weibo_id中或url（非必填）？

答：

- 问：若您已提供出错微博的weibo_id或url，可忽略此内容，否则能否提供出错账号的**user_id**及您配置的**since_date**，方便我们定位出错微博（非必填）？

答：

- 问：如果方便，请您描述出错详情，最好附上错误提示。

答：cookie错误或已过期,请按照README中方法重新获取。换另一个浏览器重复readme中操作也是此提示。

**Comment by banlangen1111** [comment]
> 可能就是cookie过期了，换个看看。

我已换过微博账号重新获取过cookie，但仍然是一样的报错。今天再重新运行一次显示了新的报错，具体如下：
(venv) D:\Projects\PythonProject\weiboSpider>python -m weibo_spider
list index out of range
Traceback (most recent call last):
  File "D:\Projects\PythonProject\weiboSpider\weibo_spider\parser\index_parser.py", line 39, in get_user
    self.user.weibo_num = string_to_int(user_info[0][3:-1])
IndexError: list index out of range
None
****************************************************************************************************
'NoneType' object has no attribute 'nickname'
Traceback (most recent call last):
  File "D:\Projects\PythonProject\weiboSpider\weibo_spider\spider.py", line 226, in _get_filepath
    dir_name = self.user.nickname
AttributeError: 'NoneType' object has no attribute 'nickname'
expected str, bytes or os.PathLike object, not NoneType
Traceback (most recent call last):
  File "D:\Projects\PythonProject\weiboSpider\weibo_spider\writer\csv_writer.py", line 25, in __init__
    with open(self.file_path, 'a', encoding='utf-8-sig',
TypeError: expected str, bytes or os.PathLike object, not NoneType
'NoneType' object has no attribute 'nickname'
Traceback (most recent call last):
  File "D:\Projects\PythonProject\weiboSpider\weibo_spider\spider.py", line 226, in _get_filepath
    dir_name = self.user.nickname
AttributeError: 'NoneType' object has no attribute 'nickname'
'NoneType' object has no attribute 'nickname'
Traceback (most recent call last):
  File "D:\Projects\PythonProject\weiboSpider\weibo_spider\spider.py", line 226, in _get_filepath
    dir_name = self.user.nickname
AttributeError: 'NoneType' object has no attribute 'nickname'
'NoneType' object has no attribute 'nickname'
Traceback (most recent call last):
  File "D:\Projects\PythonProject\weiboSpider\weibo_spider\spider.py", line 226, in _get_filepath
    dir_name = self.user.nickname
AttributeError: 'NoneType' object has no attribute 'nickname'
'NoneType' object has no attribute 'nickname'
Traceback (most recent call last):
  File "D:\Projects\PythonProject\weiboSpider\weibo_spider\spider.py", line 226, in _get_filepath
    dir_name = self.user.nickname
AttributeError: 'NoneType' object has no attribute 'nickname'
'NoneType' object has no attribute '__dict__'
Traceback (most recent call last):
  File "D:\Projects\PythonProject\weiboSpider\weibo_spider\spider.py", line 313, in get_one_user
    self.write_user(self.user)
  File "D:\Projects\PythonProject\weiboSpider\weibo_spider\spider.py", line 137, in write_user
    writer.write_user(user)
  File "D:\Projects\PythonProject\weiboSpider\weibo_spider\writer\txt_writer.py", line 29, in write_user
    [v + '：' + str(self.user.__dict__[k]) for k, v in self.user_desc])
  File "D:\Projects\PythonProject\weiboSpider\weibo_spider\writer\txt_writer.py", line 29, in <listcomp>
    [v + '：' + str(self.user.__dict__[k]) for k, v in self.user_desc])
AttributeError: 'NoneType' object has no attribute '__dict__'

**Comment by dataabc** [comment]
可能是账号被限制了，限制一段时间后会自动解除。
