### ISSUE TITLE
‘NoneType’错误

### ISSUE THREAD

**Issue by xmingpyccnu** [dataabc/weiboSpider#424]
'NoneType' object has no attribute 'xpath'
Traceback (most recent call last):
  File "C:\Software\Anaconda3\lib\site-packages\weibo_spider\parser\info_parser.py", line 21, in extract_user_info
    nickname = self.selector.xpath('//title/text()')[0]
AttributeError: 'NoneType' object has no attribute 'xpath'
'NoneType' object has no attribute 'id'
Traceback (most recent call last):
  File "C:\Software\Anaconda3\lib\site-packages\weibo_spider\parser\index_parser.py", line 36, in get_user
    self.user.id = user_id
AttributeError: 'NoneType' object has no attribute 'id'
None
##############################################
程序运行过程中会输出上面这个错误，但是程序没有中断，会继续爬取微博用户信息。
用的是user_id_list.txt存储的用户id
求解答。

**Comment by xmingpyccnu** [comment]
已解决，应该是被Ban了。
换了其他账号的cookie，放慢了速度就可以了。

**Comment by choudewanmei** [comment]
invalid literal for int() with base 10: '7.2万'
Traceback (most recent call last):
  File "C:\Users\丑的完美\AppData\Local\Programs\Python\Python39\lib\site-packages\weibo_spider\parser\index_parser.py", line 41, in get_user
    self.user.followers = int(user_info[2][3:-1])
ValueError: invalid literal for int() with base 10: '7.2万'
None
****************************************************************************************************
'NoneType' object has no attribute 'nickname'
Traceback (most recent call last):
  File "C:\Users\丑的完美\AppData\Local\Programs\Python\Python39\lib\site-packages\weibo_spider\spider.py", line 226, in _get_filepath
    dir_name = self.user.nickname
AttributeError: 'NoneType' object has no attribute 'nickname'
expected str, bytes or os.PathLike object, not NoneType
Traceback (most recent call last):
  File "C:\Users\丑的完美\AppData\Local\Programs\Python\Python39\lib\site-packages\weibo_spider\writer\csv_writer.py", line 25, in __init__
    with open(self.file_path, 'a', encoding='utf-8-sig',
TypeError: expected str, bytes or os.PathLike object, not NoneType
'NoneType' object has no attribute 'nickname'
Traceback (most recent call last):
  File "C:\Users\丑的完美\AppData\Local\Programs\Python\Python39\lib\site-packages\weibo_spider\spider.py", line 226, in _get_filepath
    dir_name = self.user.nickname
AttributeError: 'NoneType' object has no attribute 'nickname'
'NoneType' object has no attribute 'nickname'
Traceback (most recent call last):
  File "C:\Users\丑的完美\AppData\Local\Programs\Python\Python39\lib\site-packages\weibo_spider\spider.py", line 226, in _get_filepath
    dir_name = self.user.nickname
AttributeError: 'NoneType' object has no attribute 'nickname'
'NoneType' object has no attribute 'nickname'
Traceback (most recent call last):
  File "C:\Users\丑的完美\AppData\Local\Programs\Python\Python39\lib\site-packages\weibo_spider\spider.py", line 226, in _get_filepath
    dir_name = self.user.nickname
AttributeError: 'NoneType' object has no attribute 'nickname'
'NoneType' object has no attribute '__dict__'
Traceback (most recent call last):
  File "C:\Users\丑的完美\AppData\Local\Programs\Python\Python39\lib\site-packages\weibo_spider\spider.py", line 313, in get_one_user
    self.write_user(self.user)
  File "C:\Users\丑的完美\AppData\Local\Programs\Python\Python39\lib\site-packages\weibo_spider\spider.py", line 137, in write_user
    writer.write_user(user)
  File "C:\Users\丑的完美\AppData\Local\Programs\Python\Python39\lib\site-packages\weibo_spider\writer\txt_writer.py", line 29, in write_user
    [v + '：' + str(self.user.__dict__[k]) for k, v in self.user_desc])
  File "C:\Users\丑的完美\AppData\Local\Programs\Python\Python39\lib\site-packages\weibo_spider\writer\txt_writer.py", line 29, in <listcomp>
    [v + '：' + str(self.user.__dict__[k]) for k, v in self.user_desc])
AttributeError: 'NoneType' object has no attribute '__dict__'


你好，我这个是不是也是被ban了？
