### ISSUE TITLE
运行报错No module named 'absl' ，请问怎么办？

### ISSUE THREAD

**Issue by zhujn0328** [dataabc/weiboSpider#433]
我在weiboSpider-master文件夹的目录下用cmd运行python -m weibo_spider，然后弹出报错：

Traceback (most recent call last):
  File "C:\0-Nancy\0-Software\python\Python\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\0-Nancy\0-Software\python\Python\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\0-Nancy\0-Software\python\weiboSpider-master\weibo_spider\__main__.py", line 4, in <module>
    from absl import app
ModuleNotFoundError: No module named 'absl'

我用免cookie版的时候没有遇到类似错误，但是免cookie版只能跑189页，所以跑来用cookie版。但是cookie版遇到这个报错，不知道该怎么办。作者大大能看下吗？

为了更好的解决问题，请认真回答下面的问题。等到问题解决，请及时关闭本issue。

- 问：请您指明哪个版本运行出错（github版/PyPi版/全部）？

答：pip

- 问：您使用的是否是最新的程序（是/否）？

答：

- 问：爬取任意用户都会运行出错吗（是/否）？

答：是

- 问：若只有爬特定微博时才出错，能否提供出错微博的weibo_id或url（非必填）？

答：

- 问：若您已提供出错微博的weibo_id或url，可忽略此内容，否则能否提供出错账号的**user_id**及您配置的**since_date**，方便我们定位出错微博（非必填）？

答：

- 问：如果方便，请您描述出错详情，最好附上错误提示。

答：

**Comment by dataabc** [comment]
需要安装absl。

**Comment by Kevin-sunshine** [comment]
> 需要安装absl。

在cmd命令行窗口输入以下命令安装 absl

`pip install absl-py`
