### ISSUE TITLE
最近经常出现这个错误提示

### ISSUE THREAD

**Issue by gudaocode** [dataabc/weiboSpider#439]
爬取n多id时，不时出现，按目前观察，没找到有什么规律

用户昵称: 张静静Tiffany
用户id: 1312851737
微博数: 3358
关注数: 149
粉丝数: 1074000

****************************************************************************************************
****************************************************************************************************
Progress:   0%|                                                                                  | 0/1 [00:00<?, ?it/s]HTTPSConnectionPool(host='weibo.cn', port=443): Max retries exceeded with url: /1312851737?page=1 (Caused by SSLError(SSLError(1, '[SSL: BAD_SIGNATURE] bad signature (_ssl.c:997)')))
Traceback (most recent call last):
  File "C:\Users\***\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\***\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "C:\Users\***\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "C:\Users\***\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connection.py", line 362, in connect
    self.sock = ssl_wrap_socket(
  File "C:\Users\***\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\ssl_.py", line 386, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Users\***\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 512, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\***\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1070, in _create
    self.do_handshake()
  File "C:\Users\***\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1341, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: BAD_SIGNATURE] bad signature (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\***\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 440, in send
    resp = conn.urlopen(
  File "C:\Users\***\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "C:\Users\***\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\retry.py", line 446, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='weibo.cn', port=443): Max retries exceeded with url: /1312851737?page=1 (Caused by SSLError(SSLError(1, '[SSL: BAD_SIGNATURE] bad signature (_ssl.c:997)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "X:\Program Files\GS_Script_Download_WeiBo\weibo_spider\parser\util.py", line 25, in handle_html
    resp = requests.get(url, headers=headers)
  File "C:\Users\***\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\***\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\***\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\***\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\***\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='weibo.cn', port=443): Max retries exceeded with url: /1312851737?page=1 (Caused by SSLError(SSLError(1, '[SSL: BAD_SIGNATURE] bad signature (_ssl.c:997)')))
Progress:   0%|                                                                                  | 0/1 [00:03<?, ?it/s]
'NoneType' object has no attribute 'xpath'
Traceback (most recent call last):
  File "X:\Program Files\GS_Script_Download_WeiBo\weibo_spider\spider.py", line 178, in get_weibo_info
    weibos, self.weibo_id_list, to_continue = PageParser(
  File "X:\Program Files\GS_Script_Download_WeiBo\weibo_spider\parser\page_parser.py", line 45, in __init__
    info = self.selector.xpath("//div[@class='c']")
AttributeError: 'NoneType' object has no attribute 'xpath'
共爬取0条微博
信息抓取完毕

===========================================

**Comment by wowliao** [comment]
我也是这种错误，一次只能爬几百个

**Comment by dataabc** [comment]
应该是被暂时限制了，过段时间看看。
