### ISSUE TITLE
报错没有nickname属性

### ISSUE THREAD

**Issue by yhlhhhhh** [dataabc/weiboSpider#470]
系统是Mac OS，python版本是3.9
报错信息
2022-08-22 16:16:57,628 - spider.py - ERROR - 'NoneType' object has no attribute 'nickname'
Traceback (most recent call last):
  File "/Users/yanghaolin/weiboSpider/weibo_spider/spider.py", line 227, in _get_filepath
    dir_name = self.user.nickname
AttributeError: 'NoneType' object has no attribute 'nickname'
2022-08-22 16:16:57,629 - csv_writer.py - ERROR - expected str, bytes or os.PathLike object, not NoneType
Traceback (most recent call last):
  File "/Users/yanghaolin/weiboSpider/weibo_spider/writer/csv_writer.py", line 25, in __init__
    with open(self.file_path, 'a', encoding='utf-8-sig',
TypeError: expected str, bytes or os.PathLike object, not NoneType
2022-08-22 16:16:57,629 - spider.py - ERROR - 'NoneType' object has no attribute 'nickname'
Traceback (most recent call last):
  File "/Users/yanghaolin/weiboSpider/weibo_spider/spider.py", line 227, in _get_filepath
    dir_name = self.user.nickname
AttributeError: 'NoneType' object has no attribute 'nickname'
2022-08-22 16:16:57,629 - spider.py - ERROR - 'NoneType' object has no attribute '__dict__'
Traceback (most recent call last):
  File "/Users/yanghaolin/weiboSpider/weibo_spider/spider.py", line 314, in get_one_user
    self.write_user(self.user)
  File "/Users/yanghaolin/weiboSpider/weibo_spider/spider.py", line 138, in write_user
    writer.write_user(user)
  File "/Users/yanghaolin/weiboSpider/weibo_spider/writer/txt_writer.py", line 29, in write_user
    [v + '：' + str(self.user.__dict__[k]) for k, v in self.user_desc])
  File "/Users/yanghaolin/weiboSpider/weibo_spider/writer/txt_writer.py", line 29, in <listcomp>
    [v + '：' + str(self.user.__dict__[k]) for k, v in self.user_desc])
AttributeError: 'NoneType' object has no attribute '__dict__'

**Comment by dataabc** [comment]
应该是被暂时限制了，一段时间后，限制会自动解除。
