### ISSUE TITLE
程序这样报错是什么原因呢？它也可以爬下来一些用户的微博，但是不全。

### ISSUE THREAD

**Issue by zyj0301** [dataabc/weiboSpider#481]
为了更好的解决问题，请认真回答下面的问题。等到问题解决，请及时关闭本issue。

- 问：请您指明哪个版本运行出错（github版/PyPi版/全部）？

答：github版

- 问：您使用的是否是最新的程序（是/否）？

答：是

- 问：爬取任意用户都会运行出错吗（是/否）？

答：是

- 问：若只有爬特定微博时才出错，能否提供出错微博的weibo_id或url（非必填）？

答：

- 问：若您已提供出错微博的weibo_id或url，可忽略此内容，否则能否提供出错账号的**user_id**及您配置的**since_date**，方便我们定位出错微博（非必填）？

答：

- 问：如果方便，请您描述出错详情，最好附上错误提示。

答：AttributeError: 'NoneType' object has no attribute 'nickname'
expected str, bytes or os.PathLike object, not NoneType
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\weibospider\weibo_spider\writer\csv_writer.py", line 25, in __init__
    with open(self.file_path, 'a', encoding='utf-8-sig',
TypeError: expected str, bytes or os.PathLike object, not NoneType
'NoneType' object has no attribute 'nickname'
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\weibospider\weibo_spider\spider.py", line 227, in _get_filepath
    dir_name = self.user.nickname
AttributeError: 'NoneType' object has no attribute 'nickname'
'NoneType' object has no attribute '__dict__'
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\weibospider\weibo_spider\spider.py", line 314, in get_one_user
    self.write_user(self.user)
  File "C:\Users\Administrator\Desktop\weibospider\weibo_spider\spider.py", line 138, in write_user
    writer.write_user(user)
  File "C:\Users\Administrator\Desktop\weibospider\weibo_spider\writer\txt_writer.py", line 29, in write_user
    [v + '：' + str(self.user.__dict__[k]) for k, v in self.user_desc])
  File "C:\Users\Administrator\Desktop\weibospider\weibo_spider\writer\txt_writer.py", line 29, in <listcomp>
    [v + '：' + str(self.user.__dict__[k]) for k, v in self.user_desc])
AttributeError: 'NoneType' object has no attribute '__dict__'
用户昵称: 韩东言
用户id: 1874361623
微博数: 82438
关注数: 4551
粉丝数: 2275000

****************************************************************************************************
韩东言信息写入txt文件完毕，保存路径：C:\Users\Administrator\Desktop\weibospider\weibo\1874361623\1874361623.txt
****************************************************************************************************
'NoneType' object has no attribute 'xpath'
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\weibospider\weibo_spider\parser\index_parser.py", line 49, in get_page_num
    if self.selector.xpath("//input[@name='mp']") == []:
AttributeError: 'NoneType' object has no attribute 'xpath'
unsupported operand type(s) for +: 'int' and 'NoneType'
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\weibospider\weibo_spider\spider.py", line 166, in get_weibo_info
    if self.page_count > 2 and (self.page_count +
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'
共爬取0条微博
信息抓取完毕
****************************************************************************************************
'NoneType' object has no attribute 'xpath'
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\weibospider\weibo_spider\parser\index_parser.py", line 33, in get_user
    user_id = self._get_user_id()
  File "C:\Users\Administrator\Desktop\weibospider\weibo_spider\parser\index_parser.py", line 20, in _get_user_id
    url_list = self.selector.xpath("//div[@class='u']//a")
AttributeError: 'NoneType' object has no attribute 'xpath'
None

  File "C:\Users\Administrator\Desktop\weibospider\weibo_spider\spider.py", line 138, in write_user
    writer.write_user(user)
  File "C:\Users\Administrator\Desktop\weibospider\weibo_spider\writer\txt_writer.py", line 29, in write_user
    [v + '：' + str(self.user.__dict__[k]) for k, v in self.user_desc])
  File "C:\Users\Administrator\Desktop\weibospider\weibo_spider\writer\txt_writer.py", line 29, in <listcomp>
    [v + '：' + str(self.user.__dict__[k]) for k, v in self.user_desc])
AttributeError: 'NoneType' object has no attribute '__dict__'
有些能抓取到，不过总是这样报错，运行了几次没有抓取完成。

**Comment by dataabc** [comment]
可能是被暂时限制了，过段时间再看看。
