### ISSUE TITLE
程序运行出错

### ISSUE THREAD

**Issue by zjfsyh0105** [dataabc/weiboSpider#521]
为了更好的解决问题，请认真回答下面的问题。等到问题解决，请及时关闭本issue。

- 问：请您指明哪个版本运行出错（github版/PyPi版/全部）？

答：github版

- 问：您使用的是否是最新的程序（是/否）？

答：是

- 问：爬取任意用户都会运行出错吗（是/否）？

答：是

- 问：若只有爬特定微博时才出错，能否提供出错微博的weibo_id或url（非必填）？

答：

- 问：若您已提供出错微博的weibo_id或url，可忽略此内容，否则能否提供出错账号的**user_id**及您配置的**since_date**，方便我们定位出错微博（非必填）？

答：

- 问：如果方便，请您描述出错详情，最好附上错误提示。

答：
错误从4.11日开始
2023-04-13 22:40:08,127 - util.py - ERROR - HTTPSConnectionPool(host='weibo.cn', port=443): Max retries exceeded with url: /5186863057/profile (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f87098ba940>: Failed to establish a new connection: [Errno -2] Name or service not known'))
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.9/dist-packages/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connection.py", line 309, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f87098ba940>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/dist-packages/urllib3/util/retry.py", line 446, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='weibo.cn', port=443): Max retries exceeded with url: /5186863057/profile (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f87098ba940>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/weibo_spider/parser/util.py", line 25, in handle_html
    resp = requests.get(url, headers=headers)
  File "/usr/local/lib/python3.9/dist-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/dist-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='weibo.cn', port=443): Max retries exceeded with url: /5186863057/profile (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f87098ba940>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2023-04-13 22:40:08,143 - index_parser.py - ERROR - 'NoneType' object has no attribute 'xpath'
Traceback (most recent call last):
  File "/root/weibo_spider/parser/index_parser.py", line 33, in get_user
    user_id = self._get_user_id()
  File "/root/weibo_spider/parser/index_parser.py", line 20, in _get_user_id
    url_list = self.selector.xpath("//div[@class='u']//a")
AttributeError: 'NoneType' object has no attribute 'xpath'
2023-04-13 22:40:08,145 - spider.py - INFO - None
2023-04-13 22:40:08,145 - spider.py - INFO - ****************************************************************************************************
2023-04-13 22:40:08,151 - spider.py - ERROR - 'NoneType' object has no attribute 'nickname'
Traceback (most recent call last):
  File "/root/weibo_spider/spider.py", line 227, in _get_filepath
    dir_name = self.user.nickname
AttributeError: 'NoneType' object has no attribute 'nickname'
2023-04-13 22:40:08,153 - csv_writer.py - ERROR - expected str, bytes or os.PathLike object, not NoneType
Traceback (most recent call last):
  File "/root/weibo_spider/writer/csv_writer.py", line 25, in __init__
    with open(self.file_path, 'a', encoding='utf-8-sig',
TypeError: expected str, bytes or os.PathLike object, not NoneType
2023-04-13 22:40:08,154 - spider.py - ERROR - 'NoneType' object has no attribute 'nickname'
Traceback (most recent call last):
  File "/root/weibo_spider/spider.py", line 227, in _get_filepath
    dir_name = self.user.nickname
AttributeError: 'NoneType' object has no attribute 'nickname'
2023-04-13 22:40:08,155 - spider.py - INFO - ****************************************************************************************************
2023-04-13 22:40:18,163 - util.py - ERROR - HTTPSConnectionPool(host='weibo.cn', port=443): Max retries exceeded with url: /5186863057/photo?tf=6_008 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f870977f190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.9/dist-packages/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connection.py", line 309, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f870977f190>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/dist-packages/urllib3/util/retry.py", line 446, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='weibo.cn', port=443): Max retries exceeded with url: /5186863057/photo?tf=6_008 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f870977f190>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/weibo_spider/parser/util.py", line 25, in handle_html
    resp = requests.get(url, headers=headers)
  File "/usr/local/lib/python3.9/dist-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/dist-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='weibo.cn', port=443): Max retries exceeded with url: /5186863057/photo?tf=6_008 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f870977f190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2023-04-13 22:40:18,164 - spider.py - ERROR - 'NoneType' object has no attribute 'xpath'
Traceback (most recent call last):
  File "/root/weibo_spider/spider.py", line 319, in get_one_user
    self.download_user_avatar(user_config['user_uri'])
  File "/root/weibo_spider/spider.py", line 147, in download_user_avatar
    avatar_album_url = PhotoParser(self.cookie,
  File "/root/weibo_spider/parser/photo_parser.py", line 15, in extract_avatar_album_url
    result = self.selector.xpath('//img[@alt="澶村儚鐩稿唽"]/../@href')
AttributeError: 'NoneType' object has no attribute 'xpath'
2023-04-13 22:40:28,180 - util.py - ERROR - HTTPSConnectionPool(host='weibo.cn', port=443): Max retries exceeded with url: /3760069263/profile (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f870977f1c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.9/dist-packages/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connection.py", line 309, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f870977f1c0>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/dist-packages/urllib3/util/retry.py", line 446, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='weibo.cn', port=443): Max retries exceeded with url: /3760069263/profile (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f870977f1c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/weibo_spider/parser/util.py", line 25, in handle_html
    resp = requests.get(url, headers=headers)
  File "/usr/local/lib/python3.9/dist-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/dist-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='weibo.cn', port=443): Max retries exceeded with url: /3760069263/profile (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f870977f1c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2023-04-13 22:40:28,181 - index_parser.py - ERROR - 'NoneType' object has no attribute 'xpath'
Traceback (most recent call last):
  File "/root/weibo_spider/parser/index_parser.py", line 33, in get_user
    user_id = self._get_user_id()
  File "/root/weibo_spider/parser/index_parser.py", line 20, in _get_user_id
    url_list = self.selector.xpath("//div[@class='u']//a")
AttributeError: 'NoneType' object has no attribute 'xpath'
2023-04-13 22:40:28,181 - spider.py - INFO - None
2023-04-13 22:40:28,181 - spider.py - INFO - ****************************************************************************************************
2023-04-13 22:40:28,182 - spider.py - ERROR - 'NoneType' object has no attribute 'nickname'
Traceback (most recent call last):
  File "/root/weibo_spider/spider.py", line 227, in _get_filepath
    dir_name = self.user.nickname
AttributeError: 'NoneType' object has no attribute 'nickname'
2023-04-13 22:40:28,182 - csv_writer.py - ERROR - expected str, bytes or os.PathLike object, not NoneType
Traceback (most recent call last):
  File "/root/weibo_spider/writer/csv_writer.py", line 25, in __init__
    with open(self.file_path, 'a', encoding='utf-8-sig',
TypeError: expected str, bytes or os.PathLike object, not NoneType
2023-04-13 22:40:28,182 - spider.py - ERROR - 'NoneType' object has no attribute 'nickname'
Traceback (most recent call last):
  File "/root/weibo_spider/spider.py", line 227, in _get_filepath
    dir_name = self.user.nickname
AttributeError: 'NoneType' object has no attribute 'nickname'
2023-04-13 22:40:28,182 - spider.py - INFO - ****************************************************************************************************
2023-04-13 22:40:38,195 - util.py - ERROR - HTTPSConnectionPool(host='weibo.cn', port=443): Max retries exceeded with url: /3760069263/photo?tf=6_008 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f870977f0a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.9/dist-packages/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connection.py", line 309, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f870977f0a0>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/dist-packages/urllib3/util/retry.py", line 446, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='weibo.cn', port=443): Max retries exceeded with url: /3760069263/photo?tf=6_008 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f870977f0a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/weibo_spider/parser/util.py", line 25, in handle_html
    resp = requests.get(url, headers=headers)
  File "/usr/local/lib/python3.9/dist-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/dist-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='weibo.cn', port=443): Max retries exceeded with url: /3760069263/photo?tf=6_008 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f870977f0a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2023-04-13 22:40:38,196 - spider.py - ERROR - 'NoneType' object has no attribute 'xpath'
Traceback (most recent call last):
  File "/root/weibo_spider/spider.py", line 319, in get_one_user
    self.download_user_avatar(user_config['user_uri'])
  File "/root/weibo_spider/spider.py", line 147, in download_user_avatar
    avatar_album_url = PhotoParser(self.cookie,
  File "/root/weibo_spider/parser/photo_parser.py", line 15, in extract_avatar_album_url
    result = self.selector.xpath('//img[@alt="澶村儚鐩稿唽"]/../@href')
AttributeError: 'NoneType' object has no attribute 'xpath'

**Comment by dataabc** [comment]
感谢反馈。可能是速度太快，被暂时限制了，您过一段时间再看看。
