### ISSUE TITLE
程序报错list index out of range

### ISSUE THREAD

**Issue by MaoKate** [dataabc/weiboSpider#523]
为了更好的解决问题，请认真回答下面的问题。等到问题解决，请及时关闭本issue。

- 问：请您指明哪个版本运行出错（github版/PyPi版/全部）？

答：github版

- 问：您使用的是否是最新的程序（是/否）？

答：是

- 问：爬取任意用户都会运行出错吗（是/否）？

答：是

- 问：若只有爬特定微博时才出错，能否提供出错微博的weibo_id或url（非必填）？

答：

- 问：若您已提供出错微博的weibo_id或url，可忽略此内容，否则能否提供出错账号的**user_id**及您配置的**since_date**，方便我们定位出错微博（非必填）？

答：

- 问：如果方便，请您描述出错详情，最好附上错误提示。

答：
list index out of range
Traceback (most recent call last):
  File "C:\Users\kate\Downloads\weiboSpider-master\weibo_spider\parser\index_parser.py", line 39, in get_user
    self.user.weibo_num = string_to_int(user_info[0][3:-1])
IndexError: list index out of range
None
****************************************************************************************************
'NoneType' object has no attribute 'nickname'
Traceback (most recent call last):
  File "C:\Users\kate\Downloads\weiboSpider-master\weibo_spider\spider.py", line 227, in _get_filepath
    dir_name = self.user.nickname
AttributeError: 'NoneType' object has no attribute 'nickname'
expected str, bytes or os.PathLike object, not NoneType
Traceback (most recent call last):
  File "C:\Users\kate\Downloads\weiboSpider-master\weibo_spider\writer\csv_writer.py", line 26, in __init__
    newline='') as f:
TypeError: expected str, bytes or os.PathLike object, not NoneType
'NoneType' object has no attribute 'nickname'
Traceback (most recent call last):
  File "C:\Users\kate\Downloads\weiboSpider-master\weibo_spider\spider.py", line 227, in _get_filepath
    dir_name = self.user.nickname
AttributeError: 'NoneType' object has no attribute 'nickname'
'NoneType' object has no attribute 'nickname'
Traceback (most recent call last):
  File "C:\Users\kate\Downloads\weiboSpider-master\weibo_spider\spider.py", line 227, in _get_filepath
    dir_name = self.user.nickname
AttributeError: 'NoneType' object has no attribute 'nickname'
'NoneType' object has no attribute 'nickname'
Traceback (most recent call last):
  File "C:\Users\kate\Downloads\weiboSpider-master\weibo_spider\spider.py", line 227, in _get_filepath
    dir_name = self.user.nickname
AttributeError: 'NoneType' object has no attribute 'nickname'
'NoneType' object has no attribute '__dict__'
Traceback (most recent call last):
  File "C:\Users\kate\Downloads\weiboSpider-master\weibo_spider\spider.py", line 314, in get_one_user
    self.write_user(self.user)
  File "C:\Users\kate\Downloads\weiboSpider-master\weibo_spider\spider.py", line 138, in write_user
    writer.write_user(user)
  File "C:\Users\kate\Downloads\weiboSpider-master\weibo_spider\writer\txt_writer.py", line 29, in write_user
    [v + '：' + str(self.user.__dict__[k]) for k, v in self.user_desc])
  File "C:\Users\kate\Downloads\weiboSpider-master\weibo_spider\writer\txt_writer.py", line 29, in <listcomp>
    [v + '：' + str(self.user.__dict__[k]) for k, v in self.user_desc])
AttributeError: 'NoneType' object has no attribute '__dict__'

**Comment by dataabc** [comment]
应该是速度太快被暂时限制了，过一段时间再看看。

**Comment by MaoKate** [comment]
好的，我看看

**Comment by BuxinZeng** [comment]
请问解决了吗？
