### ISSUE TITLE
报错During handling of the above exception, another exception occurred

### ISSUE THREAD

**Issue by cqc01** [dataabc/weiboSpider#579]
感谢您申报bug，为了表示感谢，如果bug确实存在，您将出现在本项目的贡献者列表里；如果您不但发现了bug，还提供了很好的解决方案，我们会邀请您以pull request的方式成为本项目的代码贡献者（Contributor）；如果您多次提供很好的pull request，我们将邀请您成为本项目的协助者（Collaborator）。当然，是否提供解决方按都是自愿的。不管是否是真正的bug、是否提供解决方案，我们都感谢您对本项目的帮助。

- 问：请您指明哪个版本出了bug（github版/PyPi版/全部）？

答：github版

- 问：您使用的是否是最新的程序（是/否）？

答：是

- 问：爬取任意用户都会复现此bug吗（是/否）？

答：是

- 问：若只有爬特定微博时才出bug，能否提供出错微博的weibo_id或url（非必填）？

答：6304276977和5397477824都会报错

- 问：若您已提供出错微博的weibo_id或url，可忽略此内容，否则能否提供出错账号的**user_id**及您配置的**since_date**，方便我们定位出错微博（非必填）？

答：

- 问：如果方便，请您描述bug详情，如果代码报错，最好附上错误提示。

答：

('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1348, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 285, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:
![image](https://github.com/dataabc/weiboSpider/assets/39609327/d2383617-e635-47e3-b309-dc4731866ef1)

**Comment by dataabc** [comment]
有可能是速度太快被暂时限制了，降低速度看看。
