### ISSUE TITLE
无法使用'NoneType' object has no attribute 'nickname'，尝试过更换COOKIE

### ISSUE THREAD

**Issue by YiCheng996** [dataabc/weiboSpider#586]
为了更好的解决问题，请认真回答下面的问题。等到问题解决，请及时关闭本issue。

- 问：请您指明哪个版本运行出错（github版/PyPi版/全部）？

答：github

- 问：您使用的是否是最新的程序（是/否）？

答：是

- 问：爬取任意用户都会运行出错吗（是/否）？

答：是

- 问：若只有爬特定微博时才出错，能否提供出错微博的weibo_id或url（非必填）？

答：

- 问：若您已提供出错微博的weibo_id或url，可忽略此内容，否则能否提供出错账号的**user_id**及您配置的**since_date**，方便我们定位出错微博（非必填）？

答：1669879400

- 问：如果方便，请您描述出错详情，最好附上错误提示。

答：list index out of range
Traceback (most recent call last):
  File "C:\Users\litianhao\weiboSpider-1\weibo_spider\parser\index_parser.py", line 39, in get_user
    self.user.weibo_num = string_to_int(user_info[0][3:-1])
                                        ~~~~~~~~~^^^
IndexError: list index out of range
None
****************************************************************************************************
'NoneType' object has no attribute 'nickname'
Traceback (most recent call last):
  File "C:\Users\litianhao\weiboSpider-1\weibo_spider\spider.py", line 228, in _get_filepath
    dir_name = self.user.nickname
               ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'nickname'
expected str, bytes or os.PathLike object, not NoneType
Traceback (most recent call last):
  File "C:\Users\litianhao\weiboSpider-1\weibo_spider\writer\csv_writer.py", line 25, in __init__
    with open(self.file_path, 'a', encoding='utf-8-sig',
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected str, bytes or os.PathLike object, not NoneType
'NoneType' object has no attribute 'nickname'
Traceback (most recent call last):
  File "C:\Users\litianhao\weiboSpider-1\weibo_spider\spider.py", line 228, in _get_filepath
    dir_name = self.user.nickname
               ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'nickname'
'NoneType' object has no attribute 'nickname'
Traceback (most recent call last):
  File "C:\Users\litianhao\weiboSpider-1\weibo_spider\spider.py", line 228, in _get_filepath
    dir_name = self.user.nickname
               ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'nickname'
****************************************************************************************************
'NoneType' object has no attribute 'nickname'
Traceback (most recent call last):
  File "C:\Users\litianhao\weiboSpider-1\weibo_spider\spider.py", line 228, in _get_filepath
    dir_name = self.user.nickname
               ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'nickname'
unsupported operand type(s) for +: 'NoneType' and 'str'
Traceback (most recent call last):
  File "C:\Users\litianhao\weiboSpider-1\weibo_spider\spider.py", line 325, in get_one_user
    self.download_user_avatar(user_config['user_uri'])
  File "C:\Users\litianhao\weiboSpider-1\weibo_spider\spider.py", line 154, in download_user_avatar
    self.file_download_timeout).handle_download(pic_urls)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\litianhao\weiboSpider-1\weibo_spider\downloader\avatar_picture_downloader.py", line 14, in handle_download
    file_dir = self.file_dir + os.sep + self.describe
               ~~~~~~~~~~~~~~^~~~~~~~
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

**Comment by YiCheng996** [comment]
useragent也尝试过做更换

**Comment by YiCheng996** [comment]
目前通过切换cookie能使用了 但是还是很容易被ban 是否可以设置爬用户信息的时间间隔

**Comment by YiCheng996** [comment]
已通过cookie池解决

**Comment by 2871858184** [comment]
> 已通过cookie池解决

你好，方便问一下cookie池具体是怎么做的吗。
