### ISSUE TITLE
运行出错，无法连接

### ISSUE THREAD

**Issue by alexhill2020** [dataabc/weiboSpider#593]
为了更好的解决问题，请认真回答下面的问题。等到问题解决，请及时关闭本issue。

- 问：请您指明哪个版本运行出错（github版/PyPi版/全部）？

答：github版

- 问：您使用的是否是最新的程序（是/否）？

答：是

- 问：爬取任意用户都会运行出错吗（是/否）？

答：是

- 问：若只有爬特定微博时才出错，能否提供出错微博的weibo_id或url（非必填）？

答：

- 问：若您已提供出错微博的weibo_id或url，可忽略此内容，否则能否提供出错账号的**user_id**及您配置的**since_date**，方便我们定位出错微博（非必填）？

答：

- 问：如果方便，请您描述出错详情，最好附上错误提示。

答：安装好后，并且填上cookies后，运行“__main__.py”直接无法爬取，报如下错误，貌似是没连接上。cookies已按要求填好，无误。

错误信息：
HTTPSConnectionPool(host='weibo.cn', port=443): Max retries exceeded with url: /1669879400/profile (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:852)'),))
Traceback (most recent call last):
  File "D:\Program Files\Python36\lib\site-packages\urllib3\connectionpool.py", line 696, in urlopen
    self._prepare_proxy(conn)
  File "D:\Program Files\Python36\lib\site-packages\urllib3\connectionpool.py", line 964, in _prepare_proxy
    conn.connect()
  File "D:\Program Files\Python36\lib\site-packages\urllib3\connection.py", line 364, in connect
    conn = self._connect_tls_proxy(hostname, conn)
  File "D:\Program Files\Python36\lib\site-packages\urllib3\connection.py", line 507, in _connect_tls_proxy
    ssl_context=ssl_context,
  File "D:\Program Files\Python36\lib\site-packages\urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "D:\Program Files\Python36\lib\site-packages\urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "D:\Program Files\Python36\lib\ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "D:\Program Files\Python36\lib\ssl.py", line 817, in __init__
    self.do_handshake()
  File "D:\Program Files\Python36\lib\ssl.py", line 1077, in do_handshake
    self._sslobj.do_handshake()
  File "D:\Program Files\Python36\lib\ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:852)

**Comment by dataabc** [comment]
您参考<https://blog.csdn.net/qq_39921575/article/details/104921510>看看能否解决问题。

**Comment by alexhill2020** [comment]
经多次测试，发现是因为我开了VPN，关掉就可以正常运行了
