### ISSUE TITLE
怎么解析cookie失败

### ISSUE THREAD

**Issue by asuka1715** [dataabc/weiboSpider#619]
为了更好的解决问题，请认真回答下面的问题。等到问题解决，请及时关闭本issue。

- 问：请您指明哪个版本运行出错（github版/PyPi版/全部）？

答：github

- 问：您使用的是否是最新的程序（是/否）？

答：是

- 问：爬取任意用户都会运行出错吗（是/否）？

答：

- 问：若只有爬特定微博时才出错，能否提供出错微博的weibo_id或url（非必填）？

答：

- 问：若您已提供出错微博的weibo_id或url，可忽略此内容，否则能否提供出错账号的**user_id**及您配置的**since_date**，方便我们定位出错微博（非必填）？

答：

- 问：如果方便，请您描述出错详情，最好附上错误提示。

答：Failed to obtain weibo.cn cookie from Chrome browser: Unable to get key for cookie decryption
Check for cookie failed: Unable to get key for cookie decryption
Unable to get key for cookie decryption
Traceback (most recent call last):
  File "F:\code\weiboSpider\venv\lib\site-packages\browser_cookie3\__init__.py", line 562, in _decrypt
    return self._decrypt_windows_chromium(value, encrypted_value)
  File "F:\code\weiboSpider\venv\lib\site-packages\browser_cookie3\__init__.py", line 553, in _decrypt_windows_chromium
    _, data = _crypt_unprotect_data(encrypted_value)
  File "F:\code\weiboSpider\venv\lib\site-packages\browser_cookie3\__init__.py", line 89, in _crypt_unprotect_data
    raise RuntimeError('Failed to decrypt the cipher text with DPAPI')
RuntimeError: Failed to decrypt the cipher text with DPAPI

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\code\weiboSpider\venv\lib\site-packages\browser_cookie3\__init__.py", line 578, in _decrypt
    data = aes.decrypt_and_verify(encrypted_value[12:-16], tag)
  File "F:\code\weiboSpider\venv\lib\site-packages\Cryptodome\Cipher\_mode_gcm.py", line 567, in decrypt_and_verify
    self.verify(received_mac_tag)
  File "F:\code\weiboSpider\venv\lib\site-packages\Cryptodome\Cipher\_mode_gcm.py", line 508, in verify
    raise ValueError("MAC check failed")
ValueError: MAC check failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\code\weiboSpider\weiboSpider\weibo_spider\spider.py", line 387, in main
    config = _get_config()
  File "F:\code\weiboSpider\weiboSpider\weibo_spider\spider.py", line 376, in _get_config
    config_util.check_cookie(config_path)
  File "F:\code\weiboSpider\weiboSpider\weibo_spider\config_util.py", line 209, in check_cookie
    cookie = get_cookie()
  File "F:\code\weiboSpider\weiboSpider\weibo_spider\config_util.py", line 181, in get_cookie
    chrome_cookies = browser_cookie3.chrome(domain_name='weibo.cn')
  File "F:\code\weiboSpider\venv\lib\site-packages\browser_cookie3\__init__.py", line 1188, in chrome
    return Chrome(cookie_file, domain_name, key_file).load()
  File "F:\code\weiboSpider\venv\lib\site-packages\browser_cookie3\__init__.py", line 516, in load
    value = self._decrypt(value, enc_value, has_integrity_check_for_cookie_domain)
  File "F:\code\weiboSpider\venv\lib\site-packages\browser_cookie3\__init__.py", line 580, in _decrypt
    raise BrowserCookieError(
browser_cookie3.BrowserCookieError: Unable to get key for cookie decryption

**Comment by dataabc** [comment]
您参考下<https://stackoverflow.com/questions/79132015/browser-cookie3-browsercookieerror-unable-to-get-key-for-cookie-decryption>。

**Comment by asuka1715** [comment]
> 您参考下 https://stackoverflow.com/questions/79132015/browser-cookie3-browsercookieerror-unable-to-get-key-for-cookie-decryption。

不好意思，这个没用

**Comment by asuka1715** [comment]
这个红安县

**Comment by asuka1715** [comment]
好像跟google的安全策略有关，参考https://github.com/borisbabic/browser_cookie3/issues/210#issuecomment-2352627713

**Comment by asuka1715** [comment]
实测换到google旧版本就可以了

**Comment by dataabc** [comment]
感谢反馈。
